/* cSpell:disable */
/* eslint-disable max-lines */
/* eslint-disable max-lines-per-function */

export const cmd2Map: ReadonlyMap<string, string> = ((): ReadonlyMap<string, string> => {
    /**
     * source of https://github.com/Lexikos/Scintillua-ahk/blob/master/ahk1.lua
     * S -> string?
     * O -> output
     * E -> number
     * I -> input varName ?
     */
    const defCommand = {
        AutoTrim: 'S',
        BlockInput: 'S',
        Click: 'S',
        ClipWait: 'EE',
        Control: 'SSSSSSS',
        ControlClick: 'SSSSESSS',
        ControlFocus: 'SSSSS',
        ControlGet: 'OSSSSSSS',
        ControlGetFocus: 'OSSSS',
        ControlGetPos: 'OOOOSSSS',
        ControlGetText: 'OSSSSS',
        ControlMove: 'SEEEESSSS',
        ControlSend: 'SSSSSS',
        ControlSendRaw: 'SSSSSS',
        ControlSetText: 'SSSSSS',
        CoordMode: 'SS',
        Critical: 'S',
        DetectHiddenText: 'S',
        DetectHiddenWindows: 'S',
        Drive: 'SSS',
        DriveGet: 'OSS',
        DriveSpaceFree: 'OS',
        Edit: '',
        EnvAdd: 'OES',
        EnvDiv: 'OE',
        EnvGet: 'OS',
        EnvMult: 'OE',
        EnvSet: 'SS',
        EnvSub: 'OES',
        EnvUpdate: '',
        Exit: 'E',
        ExitApp: 'E',
        FileAppend: 'SSS',
        FileCopy: 'SSE',
        FileCopyDir: 'SSE',
        FileCreateDir: 'S',
        FileCreateShortcut: 'SSSSSSSEE',
        FileDelete: 'S',
        FileEncoding: 'S',
        FileGetAttrib: 'OS',
        FileGetShortcut: 'SOOOOOOO',
        FileGetSize: 'OSS',
        FileGetTime: 'OSS',
        FileGetVersion: 'OS',
        FileInstall: 'SSE',
        FileMove: 'SSE',
        FileMoveDir: 'SSS',
        FileRead: 'OS',
        FileReadLine: 'OSE',
        FileRecycle: 'S',
        FileRecycleEmpty: 'S',
        FileRemoveDir: 'SE',
        FileSelectFile: 'OSSSS',
        FileSelectFolder: 'OSES',
        FileSetAttrib: 'SSEE',
        FileSetTime: 'ESSEE',
        FormatTime: 'OSS',
        GetKeyState: 'OSS',
        GroupActivate: 'SS',
        GroupAdd: 'SSSSSS',
        GroupClose: 'SS',
        GroupDeactivate: 'SS',
        Gui: 'SSSS',
        GuiControl: 'SSS',
        GuiControlGet: 'OSSS',
        Hotkey: 'SSS',
        ImageSearch: 'OOEEEES',
        IniDelete: 'SSS',
        IniRead: 'OSSSS',
        IniWrite: 'SSSS',
        Input: 'OSSS',
        InputBox: 'OSSSEEEESES',
        KeyHistory: '',
        KeyWait: 'SS',
        ListHotkeys: '',
        ListLines: 'S',
        ListVars: '',
        Menu: 'SSSSSS',
        MouseClick: 'SEEEESS',
        MouseClickDrag: 'SEEEEES',
        MouseGetPos: 'OOOOE',
        MouseMove: 'EEES',
        // MsgBox: 'SSSS',
        MsgBox: 'S',
        OnExit: 'S',
        OutputDebug: 'S',
        Pause: 'SS',
        PixelGetColor: 'OEES',
        PixelSearch: 'OOEEEEEES',
        PostMessage: 'EEESSSSS',
        Process: 'SSS',
        Progress: 'SSSSS',
        Random: 'OEE',
        RegDelete: 'SS',
        RegRead: 'OSS',
        RegWrite: 'SSSS',
        Reload: '',
        Run: 'SSSO',
        RunAs: 'SSS',
        RunWait: 'SSSO',
        Send: 'S',
        SendEvent: 'S',
        SendInput: 'S',
        SendLevel: 'E',
        SendMessage: 'EEESSSSSE',
        SendMode: 'S',
        SendPlay: 'S',
        SendRaw: 'S',
        SetBatchLines: 'S',
        SetCapslockState: 'S',
        SetControlDelay: 'E',
        SetDefaultMouseSpeed: 'E',
        SetEnv: 'OS',
        SetFormat: 'SS',
        SetKeyDelay: 'EES',
        SetMouseDelay: 'ES',
        SetNumlockState: 'S',
        SetRegView: 'S',
        SetScrollLockState: 'S',
        SetStoreCapslockMode: 'S',
        SetTimer: 'SSE',
        SetTitleMatchMode: 'S',
        SetWinDelay: 'E',
        SetWorkingDir: 'S',
        Shutdown: 'E',
        Sleep: 'E',
        Sort: 'IS',
        SoundBeep: 'EE',
        SoundGet: 'OSSE',
        SoundGetWaveVolume: 'OE',
        SoundPlay: 'SS',
        SoundSet: 'ESSE',
        SoundSetWaveVolume: 'EE',
        SplashImage: 'SSSSSS',
        SplashTextOff: '',
        SplashTextOn: 'EESS',
        SplitPath: 'IOOOOO',
        StatusBarGetText: 'OESSSS',
        StatusBarWait: 'SEESSESS',
        StringCaseSense: 'S',
        StringGetPos: 'OISSE',
        StringLeft: 'OIE',
        StringLen: 'OI',
        StringLower: 'OIS',
        StringMid: 'OIEES',
        StringReplace: 'OISSS',
        StringRight: 'OIE',
        StringSplit: 'SISS',
        StringTrimLeft: 'OIE',
        StringTrimRight: 'OIE',
        StringUpper: 'OIS',
        Suspend: 'S',
        SysGet: 'OSS',
        Thread: 'SEE',
        ToolTip: 'SEEE',
        Transform: 'OSSS',
        TrayTip: 'SSEE',
        URLDownloadToFile: 'SS',
        WinActivate: 'SSSS',
        WinActivateBottom: 'SSSS',
        WinClose: 'SSESS',
        WinGet: 'OSSSSS',
        WinGetActiveStats: 'OOOOO',
        WinGetActiveTitle: 'O',
        WinGetClass: 'OSSSS',
        WinGetPos: 'OOOOSSSS',
        WinGetText: 'OSSSS',
        WinGetTitle: 'OSSSS',
        WinHide: 'SSSS',
        WinKill: 'SSESS',
        WinMaximize: 'SSSS',
        WinMenuSelectItem: 'SSSSSSSSSSS',
        WinMinimize: 'SSSS',
        WinMinimizeAll: '',
        WinMinimizeAllUndo: '',
        WinMove: 'SSEEEESS',
        WinRestore: 'SSSS',
        WinSet: 'SSSSSS',
        WinSetTitle: 'SSSSS',
        WinShow: 'SSSS',
        WinWait: 'SSESS',
        WinWaitActive: 'SSESS',
        WinWaitClose: 'SSESS',
        WinWaitNotActive: 'SSESS',
    };
    const map1 = new Map<string, string>();

    for (const [k, v] of Object.entries(defCommand)) {
        map1.set(k.toUpperCase(), v);
    }

    return map1;
})();
