/* cSpell:disable */
/* eslint-disable max-len */
/* eslint-disable max-lines */
/* eslint-disable no-template-curly-in-string */

import { EDiagCode } from '../../diag';

// TODO snippets/ahk.snippets.json
const CommandList = [
    'AUTOTRIM',
    'BETWEEN',
    'BLOCKINPUT',
    'CLASS',
    'CLICK',
    'CLIPWAIT',
    'CONTROL',
    'CONTROLCLICK',
    'CONTROLFOCUS',
    'CONTROLGET',
    'CONTROLGETFOCUS',
    'CONTROLGETPOS',
    'CONTROLGETTEXT',
    'CONTROLMOVE',
    'CONTROLSEND',
    'CONTROLSENDRAW',
    'CONTROLSETTEXT',
    'COORDMODE',
    'CRITICAL',
    'DETECTHIDDENTEXT',
    'DETECTHIDDENWINDOWS',
    'DRIVE',
    'DRIVEGET',
    'DRIVESPACEFREE',
    'EDIT',
    'ENVADD',
    'ENVDIV',
    'ENVGET',
    'ENVMULT',
    'ENVSET',
    'ENVSUB',
    'ENVUPDATE',
    'EXIT',
    'EXITAPP',
    'FILEAPPEND',
    'FILECOPY',
    'FILECOPYDIR',
    'FILECREATEDIR',
    'FILECREATESHORTCUT',
    'FILEDELETE',
    'FILEENCODING',
    'FILEGETATTRIB',
    'FILEGETSHORTCUT',
    'FILEGETSIZE',
    'FILEGETTIME',
    'FILEGETVERSION',
    'FILEINSTALL',
    'FILEMOVE',
    'FILEMOVEDIR',
    'FILEREAD',
    'FILEREADLINE',
    'FILERECYCLE',
    'FILERECYCLEEMPTY',
    'FILEREMOVEDIR',
    'FILESELECTFILE',
    'FILESELECTFOLDER',
    'FILESETATTRIB',
    'FILESETTIME',
    'FORMATTIME',
    'GETKEYSTATE',
    'GLOBAL',
    'GOSUB',
    'GOTO',
    'GROUPACTIVATE',
    'GROUPADD',
    'GROUPCLOSE',
    'GROUPDEACTIVATE',
    'GUI',
    'GUICONTROL',
    'GUICONTROLGET',
    'HOTKEY',
    'IFEXIST',
    'IFINSTRING',
    'IFMSGBOX',
    'IFNOTEXIST',
    'IFNOTINSTRING',
    'IFWINACTIVE',
    'IFWINEXIST',
    'IFWINNOTACTIVE',
    'IFWINNOTEXIST',
    'IMAGESEARCH',
    'INIDELETE',
    'INIREAD',
    'INIWRITE',
    'INPUT',
    'INPUTBOX',
    'KEYHISTORY',
    'KEYWAIT',
    'LISTHOTKEYS',
    'LISTLINES',
    'LISTVARS',
    'LOCAL',
    'MENU',
    'MOUSECLICK',
    'MOUSECLICKDRAG',
    'MOUSEGETPOS',
    'MOUSEMOVE',
    'MSGBOX',
    'OUTPUTDEBUG',
    'PAUSE',
    'PIXELGETCOLOR',
    'PIXELSEARCH',
    'POSTMESSAGE',
    'PROCESS',
    'RANDOM',
    'REGDELETE',
    'REGREAD',
    'REGWRITE',
    'RUN',
    'RUNAS',
    'RUNWAIT',
    'SEND',
    'SENDEVENT',
    'SENDINPUT',
    'SENDLEVEL',
    'SENDMESSAGE',
    'SENDMODE',
    'SENDPLAY',
    'SENDRAW',
    'SETBATCHLINES',
    'SETCAPSLOCKSTATE',
    'SETCONTROLDELAY',
    'SETDEFAULTMOUSESPEED',
    'SETFORMAT',
    'SETKEYDELAY',
    'SETMOUSEDELAY',
    'SETNUMLOCKSTATE',
    'SETREGVIEW',
    'SETSCROLLLOCKSTATE',
    'SETSTORECAPSLOCKMODE',
    'SETTIMER',
    'SETTITLEMATCHMODE',
    'SETWINDELAY',
    'SETWORKINGDIR',
    'SHUTDOWN',
    'SLEEP',
    'SORT',
    'SOUNDBEEP',
    'SOUNDGET',
    'SOUNDGETWAVEVOLUME',
    'SOUNDPLAY',
    'SOUNDSET',
    'SOUNDSETWAVEVOLUME',
    'SPLITPATH',
    'STATIC',
    'STATUSBARGETTEXT',
    'STATUSBARWAIT',
    'STRINGCASESENSE',
    'STRINGGETPOS',
    'STRINGLEFT',
    'STRINGLEN',
    'STRINGLOWER',
    'STRINGMID',
    'STRINGREPLACE',
    'STRINGRIGHT',
    'STRINGSPLIT',
    'STRINGTRIMLEFT',
    'STRINGTRIMRIGHT',
    'STRINGUPPER',
    'SUSPEND',
    'SYSGET',
    'THREAD',
    'TOOLTIP',
    'TRANSFORM',
    'TRAYTIP',
    'URLDOWNLOADTOFILE',
    'WINACTIVATE',
    'WINACTIVATEBOTTOM',
    'WINCLOSE',
    'WINGET',
    'WINGETACTIVESTATS',
    'WINGETACTIVETITLE',
    'WINGETCLASS',
    'WINGETPOS',
    'WINGETTEXT',
    'WINGETTITLE',
    'WINHIDE',
    'WINKILL',
    'WINMAXIMIZE',
    'WINMENUSELECTITEM',
    'WINMINIMIZE',
    'WINMINIMIZEALL',
    'WINMINIMIZEALLUNDO',
    'WINMOVE',
    'WINRESTORE',
    'WINSET',
    'WINSETTITLE',
    'WINSHOW',
    'WINWAIT',
    'WINWAITACTIVE',
    'WINWAITCLOSE',
    'WINWAITNOTACTIVE',
] as const;

type TCommandKeyList = typeof CommandList[number];

export type TCommandElement = {
    keyRawName: string;
    body: string;
    doc: string;
    // TODO: use DeepReadonly
    recommended?: boolean;
    link?: string;
    exp?: string[];
    diag?: EDiagCode;
};

type TLineCommand = {
    [k in TCommandKeyList]: TCommandElement;
};

export const LineCommand: TLineCommand = {
    AUTOTRIM: {
        keyRawName: 'AutoTrim',
        body: 'AutoTrim, ${1|On,Off|}',
        doc: 'Determines whether [traditional assignments](https://www.autohotkey.com/docs/commands/SetEnv.htm "Deprecated. New scripts should use Var := Value instead.") like `Var1 = %Var2%` omit spaces and tabs from the beginning and end of _Var2_.',
        recommended: false,
        link: 'https://www.autohotkey.com/docs/commands/AutoTrim.htm',
        exp: [
            'AutoTrim, OnOff',
            '; (default) On: tabs and spaces at the beginning and end of a Var2 are omitted from Var1 ',
            ';               Var1 = %Var2%',
            ';           Off: Such tabs and spaces are not omitted.',
        ],
    },
    BETWEEN: {
        keyRawName: 'between',
        body: 'between',
        doc: 'Determines whether [traditional assignments](https://www.autohotkey.com/docs/commands/SetEnv.htm "Deprecated. New scripts should use Var := Value instead.") like `Var1 = %Var2%` omit spaces and tabs from the beginning and end of _Var2_.',
        recommended: false,
        link: 'https://www.autohotkey.com/docs/commands/AutoTrim.htm',
        exp: [
            'if Var between LowerBound and UpperBound',
            'if Var not between LowerBound and UpperBound',
            '; exp',
            'var := 2',
            'if var between 1 and 5',
            '    MsgBox, % var "is in the range 1 to 5, inclusive."',
        ],
    },
    BLOCKINPUT: {
        keyRawName: 'BlockInput',
        body: 'BlockInput, ${1|On,Off,Send,Mouse,SendAndMouse,Default,MouseMove,MouseMoveOff|}',
        doc: 'Disables or enables the user\'s ability to interact with the computer via keyboard and mouse.',
        recommended: true,
        link: 'https://www.autohotkey.com/docs/commands/BlockInput.htm',
        exp: [
            'BlockInput, OnOff',
            ';  On : The user is prevented from interacting with the computer (mouse and keyboard input has no effect).',
            ';  Off: Input is re-enabled.',
            'BlockInput, SendMouse',
            ';  Send',
            ';  Mouse',
            ';  SendAndMouse',
            ';  Default',
            'BlockInput, MouseMove  ; [v1.0.43.11+]',
            ';  MouseMove',
            ';  MouseMoveOff',
        ],
    },
    CLASS: {
        keyRawName: 'Class',
        body: 'Class',
        doc: 'At its root, a "class" is a set or category of things having some property or attribute in common. Since a [base](https://www.autohotkey.com/docs/Objects.htm#Custom_Objects) or [prototype](https://www.autohotkey.com/docs/Objects.htm#Custom_Prototypes) object defines properties and behaviour for set of objects, it can also be called a _class_ object. For convenience, base objects can be defined using the "class" keyword as shown below:',
        recommended: true,
        link: 'https://www.autohotkey.com/docs/Objects.htm#Custom_Classes',
        exp: [
            'class ClassName extends BaseClassName',
            '{',
            '    InstanceVar := Expression',
            '    static ClassVar := Expression',
            '',
            '    class NestedClass',
            '    {',
            '        ...',
            '    }',
            '',
            '    Method()',
            '    {',
            '        ...',
            '    }',
            '',
            '    Property[]  ; Brackets are optional',
            '    {',
            '        get {',
            '            return ...',
            '        }',
            '        set {',
            '            return ... := value',
            '        }',
            '    }',
            '}',
        ],
    },
    CLICK: {
        keyRawName: 'Click',
        body: 'Click , Options',
        doc: 'Clicks a mouse button at the specified coordinates. It can also hold down a mouse button, turn the mouse wheel, or move the mouse.',
        recommended: true,
        link: 'https://www.autohotkey.com/docs/commands/Click.htm',
        exp: [
            ';exp1 Clicks the left mouse button at a specific position.',
            'Click, 100 200',
            '',
            ';exp2 Moves the mouse cursor to a specific position without clicking.',
            'Click, 100 200 0',
            '',
            ';exp3 Clicks the right mouse button at a specific position.',
            ' Click, 100 200 Right',
            '',
            ';exp Performs a double-click at the mouse cursor\'s current position.',
            'Click, 2',
            '',
            ';exp Presses down the left mouse button and holds it.',
            'Click, Down',
            '',
            ';exp Releases the right mouse button.',
            'Click, Up Right',
            '',
        ],
    },
    CLIPWAIT: {
        keyRawName: 'ClipWait',
        body: 'ClipWait, ${1:Timeout}, ${2|False,True|}',
        doc: 'Waits until the [clipboard](https://www.autohotkey.com/docs/misc/Clipboard.htm) contains data.',
        recommended: true,
        link: 'https://www.autohotkey.com/docs/commands/ClipWait.htm',
        exp: [
            'ClipWait , Timeout, WaitForAnyData',
            ';  Timeout : If omitted, the command will wait indefinitely.',
            ';            Else wait sec',
            ';  WaitForAnyData : ',
            '',
        ],
    },
    CONTROL: {
        keyRawName: 'Control',
        body:
            'Control, ${1|Check,Uncheck,Enable,Disable,Show,Hide,Style,ExStyle,ShowDropDown,HideDropDown,TabLeft,TabRight,Add,Delete,Choose,ChooseString,EditPaste|}',
        doc: 'Makes a variety of changes to a control.',
        recommended: true,
        link: 'https://www.autohotkey.com/docs/commands/Control.htm',
        exp: [
            'Control, SubCommand , [Value, Control, WinTitle, WinText, ExcludeTitle, ExcludeText]',
            ';  SubCommand',
            ';        Check: Turns on (checks) a radio button or checkbox.',
            ';        Uncheck: Turns off a radio button or checkbox.',
            ';        Enable: Enables a control if it was previously disabled.',
            ';        Disable: Disables or "grays out" a control.',
            ';        Show: Shows a control if it was previously hidden.',
            ';        Hide: Hides a control.',
            ';        Style: Changes the style of a control.',
            ';        ExStyle: Changes the extended style of a control.',
            ';        ShowDropDown: Shows the drop-down list of a ComboBox control.',
            ';        HideDropDown: Hides the drop-down list of a ComboBox control.',
            ';        TabLeft: Moves left by one or more tabs in a SysTabControl32.',
            ';        TabRight: Moves right by one or more tabs in a SysTabControl32.',
            ';        Add: Adds the specified string as a new entry at the bottom of a ListBox, ComboBox (and possibly other types).',
            ';        Delete: Deletes the specified entry number from a ListBox or ComboBox.',
            ';        Choose: Sets the selection in a ListBox or ComboBox to be the specified entry number.',
            ';        ChooseString: Sets the selection in a ListBox or ComboBox to be the first entry whose leading part matches the specified string.',
            ';        EditPaste: Pastes the specified string at the caret in an Edit control.',
            ';        ',
        ],
    },
    CONTROLCLICK: {
        keyRawName: 'ControlClick',
        body: 'ControlClick, ',
        doc: 'Sends a mouse button or mouse wheel event to a control.',
        recommended: true,
        link: 'https://www.autohotkey.com/docs/commands/ControlClick.htm',
        exp: [
            'ControlClick , [Control-or-Pos, WinTitle, WinText, WhichButton, ClickCount, Options, ExcludeTitle, ExcludeText]',
        ],
    },
    CONTROLFOCUS: {
        keyRawName: 'ControlFocus',
        body: 'ControlFocus, ',
        doc: 'Sets input focus to a given control on a window.',
        recommended: true,
        link: 'https://www.autohotkey.com/docs/commands/ControlFocus.htm',
        exp: [
            'ControlFocus , [Control, WinTitle, WinText, ExcludeTitle, ExcludeText]',
        ],
    },
    CONTROLGET: {
        keyRawName: 'ControlGet',
        body:
            'ControlGet, ${1:OutputVar}, ${2|List,Checked,Enabled,Visible,Tab,FindString,Choice,LineCount,CurrentLine,CurrentCol,Line,Selected,Style,ExStyle,Hwnd|}, [${3:Value}, ${4:Control}, ${5:WinTitle}, ${6:WinText}, ${7:ExcludeTitle}, ${8:ExcludeText}]',
        doc: 'Retrieves various types of information about a control.',
        recommended: true,
        link: 'https://www.autohotkey.com/docs/commands/ControlGet.htm',
        exp: [
            'ControlGet, OutputVar, SubCommand , [Value, Control, WinTitle, WinText, ExcludeTitle, ExcludeText]',
            ';SubCommand',
            ';    List: Retrieves a list of items from a ListView, ListBox, ComboBox, or DropDownList.',
            ';    Checked: Retrieves 1 if the checkbox or radio button is checked or 0 if not.',
            ';    Enabled: Retrieves 1 if the control is enabled, or 0 if disabled.',
            ';    Visible: Retrieves 1 if the control is visible, or 0 if hidden.',
            ';    Tab: Retrieves the tab number of a SysTabControl32 control.',
            ';    FindString: Retrieves the entry number of a ListBox or ComboBox that is an exact match for the string.',
            ';    Choice: Retrieves the name of the currently selected entry in a ListBox or ComboBox.',
            ';    LineCount: Retrieves the number of lines in an Edit control.',
            ';    CurrentLine: Retrieves the line number in an Edit control where the caret resides.',
            ';    CurrentCol: Retrieves the column number in an Edit control where the caret resides.',
            ';    Line: Retrieves the text of the specified line number in an Edit control.',
            ';    Selected: Retrieves the selected text in an Edit control.',
            ';    Style: Retrieves an 8-digit hexadecimal number representing the style of the control.',
            ';    ExStyle: Retrieves an 8-digit hexadecimal number representing the extended style of the control.',
            ';    Hwnd [v1.1.04+]: Retrieves the window handle (HWND) of the control.',
        ],
    },
    CONTROLGETFOCUS: {
        keyRawName: 'ControlGetFocus',
        body: 'ControlGetFocus, ${1:OutputVar}',
        doc: 'Retrieves which control of the target window has input focus, if any.',
        recommended: true,
        link: 'https://www.autohotkey.com/docs/commands/ControlGetFocus.htm',
        exp: [
            'ControlGetFocus, OutputVar , [WinTitle, WinText, ExcludeTitle, ExcludeText]',
            ';exp:',
            'ControlGetFocus, OutputVar, % "Untitled - Notepad"',
            'if ErrorLevel',
            '    MsgBox, % "The target window doesn\'t exist or none of its controls has input focus."',
            'else',
            '    MsgBox, % "Control with focus = " OutputVar',
        ],
    },
    CONTROLGETPOS: {
        keyRawName: 'ControlGetPos',
        body:
            'ControlGetPos, [{1:X}, ${2:Y}, ${3:Width}, ${4:Height}, ${5:Control}, ${6:WinTitle}, ${7:WinText}, ${8:ExcludeTitle}]',
        doc: 'Retrieves the position and size of a control.',
        recommended: true,
        link: 'https://www.autohotkey.com/docs/commands/ControlGetPos.htm',
        exp: [
            'ControlGetPos , [X, Y, Width, Height, Control, WinTitle, WinText, ExcludeTitle, ExcludeText]',
            '',
            ';exp: Continuously updates and displays the name and position of the control currently under the mouse cursor.',
            '',
            'Loop',
            '{',
            '    Sleep, 100',
            '    MouseGetPos, , , WhichWindow, WhichControl',
            '    ControlGetPos, x, y, w, h, %WhichControl%, ahk_id %WhichWindow%',
            '    ToolTip, % WhichControl "`nX: " X "`tY: " Y "`nW: " W "`tH:" H',
            '}',
        ],
    },
    CONTROLGETTEXT: {
        keyRawName: 'ControlGetText',
        body:
            'ControlGetText, ${1:OutputVar} [, ${2:Control}, ${3:WinTitle}, ${4:WinText}, ${5:ExcludeTitle}, ${6:ExcludeText]}',
        doc: 'Retrieves text from a control.\n\n* Note: To retrieve text from a ListView, ListBox, or ComboBox, use ControlGet List instead.',
        recommended: true,
        link: 'https://www.autohotkey.com/docs/commands/ControlGetText.htm',
        exp: [
            'ControlGetText, OutputVar [, Control, WinTitle, WinText, ExcludeTitle, ExcludeText]',
            '',
            ';exp 1 Retrieves the current text from Notepad\'s edit control and stores it in OutputVar.',
            '',
            '~F11::fn_test()',
            '',
            'fn_test() {',
            '    SetTitleMatchMode, 2',
            '    SetTitleMatchMode, Fast',
            '    ControlGetText, OutputVar, % "Edit1", % ".txt"',
            '    MsgBox % OutputVar',
            '}',
        ],
    },
    CONTROLMOVE: {
        keyRawName: 'ControlMove',
        body:
            'ControlMove, ${1:Control}, ${2:X}, ${3:Y}, ${4:Width}, ${5:Height} [, ${6:WinTitle}, ${7:WinText}, ${8:ExcludeTitle}]',
        doc: 'Moves or resizes a control.',
        recommended: true,
        link: 'https://www.autohotkey.com/docs/commands/ControlMove.htm',
        exp: [
            'ControlMove, Control, X, Y, Width, Height [, WinTitle, WinText, ExcludeTitle, ExcludeText]',
            '',
            ';exp',
            'fn_1 := Func("fn_ControlMoveTimer")^$',
            'SetTimer, %fn_1%',
            'InputBox, OutputVar, % "My Input Box"',
            'return',
            '',
            'fn_ControlMoveTimer() {',
            '    if not WinExist("My Input Box")',
            '        return',
            '    ; Otherwise the above set the "last found" window for us:',
            '    WinActivate',
            '    ControlMove, OK, 10, , 200 ; Move the OK button to the left and increase its width.',
            '}',
            '',
        ],
    },
    CONTROLSEND: {
        keyRawName: 'ControlSend',
        body:
            'ControlSend, [${1:Control}, ${2:Keys}, ${3:WinTitle}, ${4:WinText}, ${5:ExcludeTitle}, ${6:ExcludeText]}',
        doc: 'Sends simulated keystrokes to a window or control.',
        recommended: true,
        link: 'https://www.autohotkey.com/docs/commands/ControlSend.htm',
        exp: [
            'ControlSend [, Control, Keys, WinTitle, WinText, ExcludeTitle, ExcludeText]',
        ],
    },
    CONTROLSENDRAW: {
        keyRawName: 'ControlSendRaw',
        body:
            'ControlSendRaw, [${1:Control}, ${2:Keys}, ${3:WinTitle}, ${4:WinText}, ${5:ExcludeTitle}, ${6:ExcludeText]}',
        doc: 'Sends simulated keystrokes to a window or control.',
        recommended: true,
        link: 'https://www.autohotkey.com/docs/commands/ControlSend.htm',
        exp: [
            'ControlSendRaw [, Control, Keys, WinTitle, WinText, ExcludeTitle, ExcludeText]',
        ],
    },
    CONTROLSETTEXT: {
        keyRawName: 'ControlSetText',
        body:
            'ControlSetText, [${1:Control}, ${2:NewText }, ${3:WinTitle}, ${4:WinText}, ${5:ExcludeTitle}, ${6:ExcludeText}]',
        doc: 'Changes the text of a control.',
        recommended: true,
        link: 'https://www.autohotkey.com/docs/commands/ControlSetText.htm',
        exp: [
            'ControlSetText [, Control, NewText, WinTitle, WinText, ExcludeTitle, ExcludeText]',
        ],
    },
    COORDMODE: {
        keyRawName: 'CoordMode',
        body: 'CoordMode, ${1:ToolTip|Pixel|Mouse} [, ${2:Screen|Relative}]',
        doc: 'Sets coordinate mode for various commands to be relative to either the active window or the screen.',
        recommended: true,
        link: 'https://www.autohotkey.com/docs/commands/CoordMode.htm',
        exp: [
            'CoordMode, TargetType [, RelativeTo]',
            'CoordMode, ToolTip, Screen',
            'CoordMode, ToolTip',
        ],
    },
    CRITICAL: {
        keyRawName: 'Critical',
        body: 'Critical, ${1|Off,On|}',
        doc: 'Prevents the current thread from being interrupted by other threads, or enables it to be interrupted.',
        recommended: true,
        link: 'https://www.autohotkey.com/docs/commands/CoordMode.htm',
        exp: [
            'Critical [, OnOffNumeric]',
            ';          TargetType',
            ';                 -> On (defaults)',
            ';                 -> Off',
        ],
    },
    DETECTHIDDENTEXT: {
        keyRawName: 'DetectHiddenText',
        body: 'DetectHiddenText, ${1:On|Off}',
        doc: 'Determines whether invisible text in a window is "seen" for the purpose of finding the window. This affects commands, built-in functions and control flow statements such as WinExist() and WinActivate.',
        recommended: true,
        link: 'https://www.autohotkey.com/docs/commands/DetectHiddenText.htm',
        exp: [
            'DetectHiddenText, OnOff',
            ';                -> On (defaults), Hidden text will be detected.',
            ';                -> Off, Hidden text is not detected.',
        ],
    },
    DETECTHIDDENWINDOWS: {
        keyRawName: 'DetectHiddenWindows',
        body: 'DetectHiddenWindows, ${1:On|Off}',
        doc: 'Determines whether invisible windows are "seen" by the script.',
        recommended: true,
        link: 'https://www.autohotkey.com/docs/commands/DetectHiddenWindows.htm',
        exp: [
            'DetectHiddenWindows, OnOff',
            ';                     On: Hidden windows are detected.',
            ';          (default) Off: Hidden windows are not detected, except by the WinShow command.',
        ],
    },
    DRIVE: {
        keyRawName: 'Drive',
        body: 'Drive, ${1|Label,Lock,Unlock,Eject|} [, ${2:Drive}, ${3:Value}]',
        doc: 'Ejects/retracts the tray in a CD or DVD drive, or sets a drive\'s volume label.',
        recommended: true,
        link: 'https://www.autohotkey.com/docs/commands/Drive.htm',
        exp: [
            'Drive, SubCommand , Value1, Value2',
            ';      SubCommand',
            ';          Label: Renames the volume label of a drive.',
            ';          Lock: Prevents a drive\'s eject feature from working.',
            ';          Unlock: Restores a drive\'s eject feature.',
            ';          Eject: Ejects or retracts the tray of a CD or DVD drive.',
        ],
    },
    DRIVEGET: {
        keyRawName: 'DriveGet',
        body:
            'DriveGet, ${1:OutputVar}, ${2|List,Capacity,FileSystem,Label,Serial,Type,Status,StatusCD|} [, ${3:Value}]',
        doc: [
            'Retrieves various types of information about the computer\'s drive(s).',
            '*SubCommand*',
            '* List:        Retrieves a string of letters, one character for each drive letter in the system.',
            '* Capacity:    Retrieves the total capacity of the specified path in megabytes.',
            '* FileSystem:  Retrieves the type of the specified drive\'s file system.',
            '* Label:       Retrieves the volume label of the specified drive.',
            '* Serial:      Retrieves the volume serial number of the specified drive.',
            '* Type:        Retrieves the drive type of the specified path.',
            '* Status:      Retrieves the status of the specified path.',
            '* StatusCD:    Retrieves the media status of a CD or DVD drive.',
        ].join('\n'),
        recommended: true,
        link: 'https://www.autohotkey.com/docs/commands/DriveGet.htm',
        exp: [
            'DriveGet, OutputVar, SubCommand [, Value]',
            '',
            ';exp Allows the user to select a drive in order to analyze it.',
            '',
            'FileSelectFolder, folder,, 3, Pick a drive to analyze:',
            'if not folder',
            '    return',
            'DriveGet, list, List',
            'DriveGet, cap, Capacity, %folder%',
            'DriveSpaceFree, free, %folder%',
            'DriveGet, fs, FileSystem, %folder%',
            'DriveGet, label, Label, %folder%',
            'DriveGet, serial, Serial, %folder%',
            'DriveGet, type, Type, %folder%',
            'DriveGet, status, Status, %folder%',
            'MsgBox All Drives: %list%`nSelected Drive: %folder%`nDrive Type: %type%`nStatus: %status%`nCapacity: %cap% M`nFree Space: %free% M`nFilesystem: %fs%`nVolume Label: %label%`nSerial Number: %serial%',
        ],
    },
    DRIVESPACEFREE: {
        keyRawName: 'DriveSpaceFree',
        body: 'DriveSpaceFree, ${1:OutputVar_MBSize}, ${2:C:\\}',
        doc: 'Retrieves the free disk space of a drive, in Megabytes.',
        recommended: true,
        link: 'https://www.autohotkey.com/docs/commands/DriveSpaceFree.htm',
        exp: [
            'DriveSpaceFree, OutputVar, Path',
            '; OutputVar size is Megabytes.',
            '',
            'DriveSpaceFree, FreeSpace, C:\\',
            'MsgBox % FreeSpace//1024 ; MB -> GB',
        ],
    },
    EDIT: {
        keyRawName: 'Edit',
        body: 'Edit',
        doc: 'Opens the current script for editing in the associated editor.',
        recommended: true,
        link: 'https://www.autohotkey.com/docs/commands/Edit.htm',
        exp: [
            'Edit',
        ],
    },
    ENVADD: {
        keyRawName: 'EnvAdd',
        body: 'EnvAdd, ${1:Var}, ${2:Value} [, ${3:TimeUnits]}',
        doc: 'Sets a [variable](https://www.autohotkey.com/docs/Variables.htm) to the sum of itself plus the given value (can also add or subtract time from a [date-time](https://www.autohotkey.com/docs/commands/FileSetTime.htm#YYYYMMDD) value). Synonymous with: `Var += Value`.',
        recommended: true,
        link: 'https://www.autohotkey.com/docs/commands/EnvAdd.htm',
        exp: [
            'EnvAdd, Var, Value , TimeUnits',
            'Var += Value , TimeUnits',
            'Var++',
            ';-----',
            '; exp 1',
            'var1 := ""  ; Make it blank so that the below will use the current timestamp instead.',
            'var1 += 31, days',
            'MsgBox, % var1  ; The answer will be the date 31 days from now.',
        ],
    },
    ENVDIV: {
        keyRawName: 'EnvDiv',
        body: 'EnvDiv, ${1:Var}, ${2:Value}',
        doc: 'Sets a [variable](https://www.autohotkey.com/docs/Variables.htm) to itself divided by the given value. Synonymous with: `Var /= Value`.',
        recommended: false,
        link: 'https://www.autohotkey.com/docs/commands/EnvDiv.htm',
        exp: [
            'EnvDiv, Var, Value',
            'EnvDiv, MyCount, 2',
            'MyCount /= 2',
        ],
        diag: EDiagCode.code803,
    },
    ENVGET: {
        keyRawName: 'EnvGet',
        body: 'EnvGet, ${1:OutputVar}, ${2:EnvVarName}',
        doc: [
            'Retrieves an environment variable.',
            '# [Parameters](https://www.autohotkey.com/docs/commands/EnvGet.htm#Parameters)',
            '* OutputVar : ',
            '  The name of the variable in which to store the string.',
            '* EnvVarName :',
            '  The name of the [environment variable](https://www.autohotkey.com/docs/Concepts.htm#environment-variables) to retrieve.',
            '  Exp : `Path` or `TEMP`or `TMP`',
        ].join('\n'),
        recommended: true,
        link: 'https://www.autohotkey.com/docs/commands/EnvGet.htm',
        exp: [
            'EnvGet, OutputVar, % A_Is64bitOS ? "ProgramW6432" : "ProgramFiles"',
            'MsgBox, % "Program files are in: " OutputVar',
        ],
    },
    ENVMULT: {
        keyRawName: 'EnvMult',
        body: 'EnvMult, ${1:Var}, ${2:Value}',
        doc: 'Sets a [variable](https://www.autohotkey.com/docs/Variables.htm) to itself times the given value. Synonymous with: `Var *= Value`.',
        recommended: false,
        link: 'https://www.autohotkey.com/docs/commands/EnvMult.htm',
        exp: [
            'EnvMult, Var, Value',
            'EnvMult, MyCount, 2',
            'MyCount *= 2',
        ],
        diag: EDiagCode.code804,
    },
    ENVSET: {
        keyRawName: 'EnvSet',
        body: 'EnvSet, ${1:EnvVar}, ${2:Value}',
        doc: [
            'Writes a value to a [variable](https://www.autohotkey.com/docs/Variables.htm) contained in the environment.',
            '## Parameters',
            '* EnvVar : ',
            '  Name of the [environment variable](https://www.autohotkey.com/docs/Concepts.htm#environment-variables) to use, e.g. "COMSPEC" or "PATH".',
            '* Value :',
            '  Value to set the [environment variable](https://www.autohotkey.com/docs/Concepts.htm#environment-variables) to.',
        ].join('\n'),
        recommended: true,
        link: 'https://www.autohotkey.com/docs/commands/EnvSet.htm',
        exp: [
            'EnvSet, AutGUI, Some text to put in the variable.',
        ],
    },
    ENVSUB: {
        keyRawName: 'EnvSub',
        body: 'EnvSub, ${1:Var}, ${2:Value}, ${3|Seconds,Minutes,Hours,Days|}',
        doc: [
            'Sets a [variable](https://www.autohotkey.com/docs/Variables.htm) to itself minus the given value (can also compare [date-time](https://www.autohotkey.com/docs/commands/FileSetTime.htm#YYYYMMDD) values). Synonymous with: `Var -= Value`.',
            '## [Parameters](https://www.autohotkey.com/docs/commands/EnvSub.htm#Parameters)',
            '* Var : ',
            '  The name of the [variable](https://www.autohotkey.com/docs/Variables.htm) upon which to operate.',
            '* Value :',
            '  Any integer, floating point number, or [expression](https://www.autohotkey.com/docs/Variables.htm#Expressions).',
            '* TimeUnits \n',
            '> `Seconds`, `Minutes`, `Hours`, `Days`\n',
        ].join('\n'),
        recommended: true,
        link: 'https://www.autohotkey.com/docs/commands/EnvSub.htm',
        exp: [
            'var1 := 20050126',
            'var2 := 20040126',
            'EnvSub, var1, %var2%, Days',
            'MsgBox, %var1%  ; The answer will be 366 since 2004 is a leap year.',
        ],
    },
    ENVUPDATE: {
        keyRawName: 'EnvUpdate',
        body: 'EnvUpdate',
        doc: 'Notifies the OS and all running applications that [environment variable(s)](https://www.autohotkey.com/docs/Concepts.htm#environment-variables) have changed.',
        recommended: true,
        link: 'https://www.autohotkey.com/docs/commands/EnvUpdate.htm',
        exp: [
            'EnvUpdate',
        ],
    },
    EXIT: {
        keyRawName: 'Exit',
        body: 'Exit [, ${1:ExitCode}]',
        doc: [
            'Exits the [current thread](https://www.autohotkey.com/docs/misc/Threads.htm) or (if the script is not [persistent](https://www.autohotkey.com/docs/commands/_Persistent.htm)) the entire script.',
            '* ExitCode',
            '',
            '> An integer between -2147483648 and 2147483647 (can be an [expression](https://www.autohotkey.com/docs/Variables.htm#Expressions)) that is returned to its caller when the script exits. This code is accessible to any program that spawned the script, such as another script (via RunWait) or a batch (.bat) file. If omitted, _ExitCode_ defaults to zero. Zero is traditionally used to indicate success.',
        ].join('\n'),
        recommended: true,
        link: 'https://www.autohotkey.com/docs/commands/Exit.htm',
        exp: [
            '#z::',
            '    Gosub, Sub2',
            '    MsgBox, % "This MsgBox will never happen because of the EXIT."',
            'Return',
            '',
            'Sub2:',
            'Exit  ; Terminate this subroutine as well as the calling subroutine.',
        ],
    },
    EXITAPP: {
        keyRawName: 'ExitApp',
        body: 'ExitApp [, ${1:ExitCode}]',
        doc: [
            'Terminates the script.',
            '* ExitCode',
            '1. An integer between -2147483648 and 2147483647',
            '2. If omitted, _ExitCode_ defaults to zero.',
            '3. Zero is traditionally used to indicate success.',
            '\n\n',
        ].join('\n'),
        recommended: true,
        link: 'https://www.autohotkey.com/docs/commands/ExitApp.htm',
        exp: [
            'ExitApp [, ExitCode]',
            '',
            ';exp Press a hotkey to terminate the script.',
            '#x::ExitApp  ; Win+X',
        ],
    },
    FILEAPPEND: {
        keyRawName: 'FileAppend',
        body: 'FileAppend [, ${1:Text}, ${2:Filename}, ${3:Encoding}]',
        doc: 'Writes text to the end of a file (first creating the file, if necessary).',
        recommended: false,
        link: 'https://www.autohotkey.com/docs/commands/FileAppend.htm',
        exp: [
            'FileAppend , Text, Filename, Encoding',
            '',
            'Var := "~~ your var~~"',
            'FileAppend,',
            '(',
            'A line of text.',
            'By default, the hard carriage return (Enter) between the previous line and this one will be written to the file.',
            '    This line is indented with a tab; by default, that tab will also be written to the file.',
            'Variable references such as %Var% are expanded by default.',
            '), D:\\My File.txt',
        ],
        diag: EDiagCode.code700,
    },
    FILECOPY: {
        keyRawName: 'FileCopy',
        body: 'FileCopy, ${1:Source}, ${2:Dest} [, ${3|0,1|}]',
        doc: [
            'Copies one or more files.',
            '* Overwrite',
            '* If omitted or 0 (false), the command does not overwrite existing files.',
            '* If this parameter is 1 (true), the command overwrites existing files.',
            '',
        ].join('\n'),
        recommended: true,
        link: 'https://www.autohotkey.com/docs/commands/FileCopy.htm',
        exp: [
            'FileCopy, SourcePattern, DestPattern [, Overwrite]',
            '',
            ';exp1 Makes a copy but keep the original file name.',
            'FileCopy, C:\\My Documents\\List1.txt, D:\\Main Backup\\',
        ],
    },
    FILECOPYDIR: {
        keyRawName: 'FileCopyDir',
        body: 'FileCopyDir, ${1:Source}, ${2:Dest} [, ${3|0,1|}]',
        doc: [
            'Copies a folder along with all its sub-folders and files (similar to xcopy).',
            '* **Overwrite**',
            '* This parameter determines whether to overwrite files if they already exist. If omitted, it defaults to 0 (false). Specify one of the following values:',
            '* 0 (false): Do not overwrite existing files. The operation will fail and have no effect if _Dest_ already exists as a file or directory.',
            '* 1 (true): Overwrite existing files. However, any files or subfolders inside _Dest_ that do not have a counterpart in _Source_ will not be deleted.',
            '* This parameter can be an [expression](https://www.autohotkey.com/docs/Variables.htm#Expressions), even one that evalutes to true or false (since true and false are stored internally as 1 and 0).',
            '',
        ].join('\n'),
        recommended: true,
        link: 'https://www.autohotkey.com/docs/commands/FileCopyDir.htm',
        exp: [
            'FileCopyDir, Source, Dest [, Overwrite]',
            '',
            ';exp1 Copies a directory to a new location.',
            'FileCopyDir, % "C:\\My Folder", % "C:\\Copy of My Folder"',
        ],
    },
    FILECREATEDIR: {
        keyRawName: 'FileCreateDir',
        body: 'FileCreateDir, ${1:Path}',
        doc: 'Creates a folder.',
        recommended: true,
        link: 'https://www.autohotkey.com/docs/commands/FileCreateDir.htm',
        exp: [
            'FileCreateDir, DirName',
            '',
            ';exp1 Creates a new directory, including its parent directories if necessary.',
            'FileCreateDir, % "C:\\Test1\\My Images\\Folder2"',
        ],
    },
    FILECREATESHORTCUT: {
        keyRawName: 'FileCreateShortcut',
        body:
            'FileCreateShortcut, ${1:Target}, ${2:C:\\My Shortcut.lnk } [, ${3:WorkingDir}, ${4:Args}, ${5:Description}, ${6:IconFile}, ${7:ShortcutKey}, ${8:IconNumber}, ${9|1,3,7|}',
        doc: 'Creates a shortcut (.lnk) file.',
        recommended: true,
        link: 'https://www.autohotkey.com/docs/commands/FileCreateShortcut.htm',
        exp: [
            'FileCreateShortcut, Target, LinkFile [, WorkingDir, Args, Description, IconFile, ShortcutKey, IconNumber, RunState]',
            '',
            ';exp1 The letter "i" in the last parameter makes the shortcut key be Ctrl+Alt+I.',
            'FileCreateShortcut, Notepad.exe, %A_Desktop%\\My Shortcut.lnk, C:\\, "%A_ScriptFullPath%", My Description, C:\\My Icon.ico, i',
        ],
    },
    FILEDELETE: {
        keyRawName: 'FileDelete',
        body: 'FileDelete, ${1:FilePattern}',
        doc: [
            'Deletes one or more files.',
            '',
            '### FilePattern',
            '1. The name of a single file or a wildcard pattern such as `C:\\Temp\\*.tmp`. _FilePattern_ is assumed to be in [%A\\_WorkingDir%](https://www.autohotkey.com/docs/Variables.htm#WorkingDir) if an absolute path isn\'t specified.',
            '',
            '2. To remove an entire folder, along with all its sub-folders and files, use [FileRemoveDir](https://www.autohotkey.com/docs/commands/FileRemoveDir.htm).',
        ].join('\n'),
        recommended: true,
        link: 'https://www.autohotkey.com/docs/commands/FileDelete.htm',
        exp: [
            'FileDelete, FilePattern',
            '',
            ';exp1 Deletes all .tmp files in a directory.',
            'FileDelete, C:\\temp files\\*.tmp',
        ],
    },
    FILEENCODING: {
        keyRawName: 'FileEncoding',
        body: 'FileEncoding, [${1|ANSI,UTF-8,UTF-8-RAW,UTF-16,UTF-16-RAW,CPnnn|}]',
        doc: [
            'Sets the default encoding for [FileRead](https://www.autohotkey.com/docs/commands/FileRead.htm), [FileReadLine](https://www.autohotkey.com/docs/commands/FileReadLine.htm), [Loop Read](https://www.autohotkey.com/docs/commands/LoopReadFile.htm), [FileAppend](https://www.autohotkey.com/docs/commands/FileAppend.htm), and [FileOpen()](https://www.autohotkey.com/docs/commands/FileOpen.htm).',
            '',
            '### Encoding',
            'One of the following values :',
            '(if omitted, it defaults to the system default ANSI code page, which is also the default setting)',
            '**UTF-8:** Unicode UTF-8, equivalent to CP65001.\n',
            '**UTF-8-RAW:** As above, but no byte order mark is written when a new file is created.\n',
            '**UTF-16:** Unicode UTF-16 with little endian byte order, equivalent to CP1200.\n',
            '**UTF-16-RAW:** As above, but no byte order mark is written when a new file is created.\n',
            '**CP_nnn_:** A code page with numeric identifier _nnn_. See [Code Page Identifiers](http://msdn.microsoft.com/en-us/library/dd317756.aspx).\n',
        ].join('\n'),
        recommended: true,
        link: 'https://www.autohotkey.com/docs/commands/FileEncoding.htm',
        exp: [
            'FileEncoding [, Encoding]',
            '',
        ],
    },
    FILEGETATTRIB: {
        keyRawName: 'FileGetAttrib',
        body: 'FileGetAttrib, ${1:OutputVar} , [${2:Filename}]',
        doc: [
            'Reports whether a file or folder is read-only, hidden, etc.',
            '\n',
            '### Remarks,',
            'The string returned will contain a subset of the letters in the string "RASHNDOCT":\n',
            '\n',
            '- R = READONLY\n',
            '- A = ARCHIVE\n',
            '- S = SYSTEM\n',
            '- H = HIDDEN\n',
            '- N = NORMAL\n',
            '- D = DIRECTORY\n',
            '- O = OFFLINE\n',
            '- C = COMPRESSED\n',
            '- T = TEMPORARY\n',
        ].join('\n'),
        recommended: false,
        link: 'https://www.autohotkey.com/docs/commands/FileGetAttrib.htm',
        exp: [
            'FileGetAttrib, OutputVar , Filename',
            ';exp',
            'FileGetAttrib, OutputVar, % "C:\\New Folder"',
            '',
            ';exp2 : To check if a particular attribute is present in the retrieved string, following this example:',
            'FileGetAttrib, Attributes, C:\\My File.txt',
            'if InStr(Attributes, "H")',
            '    MsgBox The file is hidden.',
        ],
        diag: EDiagCode.code700,
    },
    FILEGETSHORTCUT: {
        keyRawName: 'FileGetShortcut',
        body:
            'FileGetShortcut, ${1:LinkFile} [, ${2:OutTarget}, ${3:OutDir}, ${4:OutArgs}, ${5:Outdoc}, ${6:OutIcon}, ${7:OutIconNum}, ${8:OutRunState}]',
        doc: [
            'Retrieves information about a shortcut (.lnk) file, such as its target file.',
            '## [Parameters](https://www.autohotkey.com/docs/commands/FileGetShortcut.htm#Parameters)\n',
            '',
            'LinkFile',
            '',
            'Name of the shortcut file to be analyzed, which is assumed to be in [%A\\_WorkingDir%](https://www.autohotkey.com/docs/Variables.htm#WorkingDir) if an absolute path isn\'t specified. Be sure to include the **.lnk** extension.\n',
            '',
            'OutTarget',
            '',
            'Name of the variable in which to store the shortcut\'s target (not including any arguments it might have). For example: C:\\WINDOWS\\system32\\notepad.exe\n',
            '',
            'OutDir\n',
            '',
            'Name of the variable in which to store the shortcut\'s working directory. For example: C:\\My Documents. If environment variables such as %WinDir% are present in the string, one way to resolve them is via [StrReplace()](https://www.autohotkey.com/docs/commands/StrReplace.htm) or [StringReplace](https://www.autohotkey.com/docs/commands/StringReplace.htm "Deprecated. New scripts should use StrReplace() instead."). For example: [StringReplace](https://www.autohotkey.com/docs/commands/StringReplace.htm), OutDir, OutDir, `%WinDir`%, %[A_WinDir](https://www.autohotkey.com/docs/Variables.htm#WinDir)%.\n',
            '',
            'OutArgs\n',
            '',
            'Name of the variable in which to store the shortcut\'s parameters (blank if none).\n',
            '',
            'OutDescription\n',
            '',
            'Name of the variable in which to store the shortcut\'s comments (blank if none).\n',
            '',
            'OutIcon\n',
            '',
            'Name of the variable in which to store the filename of the shortcut\'s icon (blank if none).\n',
            '',
            'OutIconNum\n',
            '',
            'Name of the variable in which to store the shortcut\'s icon number within the icon file (blank if none). This value is most often 1, which means the first icon.\n',
            '',
            'OutRunState\n',
            'Name of the variable in which to store the shortcut\'s initial launch state, which is one of the following digits:',
            '- 1 = Normal',
            '- 3 = Maximized',
            '- 7 = Minimized',
        ].join('\n'),
        recommended: true,
        link: 'https://www.autohotkey.com/docs/commands/FileGetShortcut.htm',
        exp: [
            'FileGetShortcut, LinkFile [, OutTarget, OutDir, OutArgs, OutDescription, OutIcon, OutIconNum, OutRunState]',
        ],
    },
    FILEGETSIZE: {
        keyRawName: 'FileGetSize',
        body: 'FileGetSize, ${1:OutputVar [}, ${2:Filename}, ${3:Units]}',
        doc: 'Retrieves the size of a file.',
        // FIXME: add docs
    },
    FILEGETTIME: {
        keyRawName: 'FileGetTime',
        body: 'FileGetTime, ${1:OutputVar [}, ${2:Filename}, ${3:WhichTime (M}, ${4:C}, ${5:or A -- default is M)]}',
        doc: 'Retrieves the datetime stamp of a file or folder.',
    },
    FILEGETVERSION: {
        keyRawName: 'FileGetVersion',
        body: 'FileGetVersion, ${1:OutputVar [}, ${2:Filename]}',
        doc: 'Retrieves the version of a file.',
    },
    FILEINSTALL: {
        keyRawName: 'FileInstall',
        body: 'FileInstall, ${1:Source}, ${2:Dest [}, ${3:Flag (1 = overwrite)]}',
        doc: 'Includes the specified file inside the compiled version of the script.',
    },
    FILEMOVE: {
        keyRawName: 'FileMove',
        body: 'FileMove, ${1:Source}, ${2:Dest [}, ${3:Flag (1 = overwrite)]}',
        doc: 'Moves or renames one or more files.',
    },
    FILEMOVEDIR: {
        keyRawName: 'FileMoveDir',
        body: 'FileMoveDir, ${1:Source}, ${2:Dest [}, ${3:Flag (2 = overwrite)]}',
        doc: 'Moves a folder along with all its sub-folders and files. It can also rename a folder.',
    },
    FILEREAD: {
        keyRawName: 'FileRead',
        body: 'FileRead, ${1:OutputVar}, ${2:Filename}',
        doc: 'Reads a file\'s contents into a [variable](https://www.autohotkey.com/docs/Variables.htm).',
        recommended: false,
        exp: [
            'FileRead, OutputVar, % "C:\\My Documents\\My File.txt"',
        ],
        diag: EDiagCode.code700,
    },
    FILEREADLINE: {
        keyRawName: 'FileReadLine',
        body: 'FileReadLine, ${1:OutputVar}, ${2:Filename}, ${3:LineNum}',
        doc: 'Reads the specified line from a file and stores the text in a variable.',
    },
    FILERECYCLE: {
        keyRawName: 'FileRecycle',
        body: 'FileRecycle, ${1:FilePattern}',
        doc: 'Sends a file or directory to the recycle bin if possible, or permanently deletes it.',
    },
    FILERECYCLEEMPTY: {
        keyRawName: 'FileRecycleEmpty',
        body: 'FileRecycleEmpty, ${1:[ C:\\]}',
        doc: 'Empties the recycle bin.',
    },
    FILEREMOVEDIR: {
        keyRawName: 'FileRemoveDir',
        body: 'FileRemoveDir, ${1:Path [}, ${2:Recurse? (1 = yes)]}',
        doc: 'Deletes a folder.',
    },
    FILESELECTFILE: {
        keyRawName: 'FileSelectFile',
        body:
            'FileSelectFile, ${1:OutputVar [}, ${2:Options}, ${3:RootDir[\\DefaultFilename]}, ${4:Prompt}, ${5:Filter]}',
        doc: 'Displays a standard dialog that allows the user to open or save file(s).',
    },
    FILESELECTFOLDER: {
        keyRawName: 'FileSelectFolder',
        body: 'FileSelectFolder, ${1:OutputVar [}, ${2:*StartingFolder}, ${3:Options}, ${4:Prompt]}',
        doc: 'Displays a standard dialog that allows the user to select a folder.',
    },
    FILESETATTRIB: {
        keyRawName: 'FileSetAttrib',
        body: 'FileSetAttrib, ${1:Attributes(+-^RASHNOT) [}, ${2:FilePattern}, ${3:OperateOnFolders?}, ${4:Recurse?]}',
        doc: 'Changes the attributes of one or more files or folders. Wildcards are supported.',
    },
    FILESETTIME: {
        keyRawName: 'FileSetTime',
        body:
            'FileSetTime, ${1:[ YYYYMMDDHH24MISS}, ${2:FilePattern}, ${3:WhichTime (M|C|A)}, ${4:OperateOnFolders?}, ${5:Recurse?]}',
        doc: 'Changes the datetime stamp of one or more files or folders. Wildcards are supported.',
    },
    FORMATTIME: {
        keyRawName: 'FormatTime',
        body: 'FormatTime, ${1:OutputVar [}, ${2:YYYYMMDDHH24MISS}, ${3:Format]}',
        doc: 'Transforms a YYYYMMDDHH24MISS timestamp into the specified date/time format.',
    },
    GETKEYSTATE: {
        keyRawName: 'GetKeyState',
        body: 'GetKeyState, ${1:OutputVar}, ${2:KeyName} [,${3:Mode}]',
        doc: '**Deprecated:** This command is not recommended for use in new scripts. Use the [GetKeyState](https://www.autohotkey.com/docs/commands/GetKeyState.htm#function) function instead.',
        recommended: false,
        link: 'https://www.autohotkey.com/docs/commands/GetKeyState.htm#command',
        exp: [
            'GetKeyState, OutputVar, KeyName , Mode',
            ' ',
            'KeyIsDown := GetKeyState(KeyName , Mode)',
        ],
        diag: EDiagCode.code700,
    },
    GLOBAL: {
        keyRawName: 'global',
        body: 'global',
        doc: 'To refer to an existing global variable inside a function (or create a new one), declare the variable as global prior to using it.',
        recommended: true,
        link: 'https://www.autohotkey.com/docs/Functions.htm#Global',
        exp: [
            'global LogFileName  ; This global variable was previously given a value somewhere outside this function.',
        ],
    },
    GOSUB: {
        keyRawName: 'Gosub',
        body: 'Gosub, ${1:Label}',
        doc: 'Jumps to the specified label and continues execution until [Return](https://www.autohotkey.com/docs/commands/Return.htm) is encountered.',
        recommended: false,
        link: 'https://www.autohotkey.com/docs/commands/Gosub.htm',
        exp: [
            'Gosub, Label1 ',
            '    MsgBox, The Label1 subroutine has returned (it is finished).',
            'return',
            '',
            'Label1:',
            '    MsgBox, The Label1 subroutine is now running.',
            'return',
        ],
    },
    GOTO: {
        keyRawName: 'Goto',
        body: 'Goto, ${1:Label}',
        doc: 'Jumps to the specified label and continues execution.',
        recommended: false,
        link: 'https://www.autohotkey.com/docs/commands/Goto.htm',
        exp: [
            'Goto, MyLabel',
            '',
            '; ...',
            '',
            'MyLabel:',
            '',
            'Sleep, 100',
            '; ...',
            '',
        ],
    },
    GROUPACTIVATE: {
        keyRawName: 'GroupActivate',
        body: 'GroupActivate, ${1:GroupName [}, ${2:R]}',
        doc: 'Activates the next window in a window group that was defined with GroupAdd.',
    },
    GROUPADD: {
        keyRawName: 'GroupAdd',
        body:
            'GroupAdd, ${1:GroupName}, ${2:WinTitle [}, ${3:WinText}, ${4:Label}, ${5:ExcludeTitle}, ${6:ExcludeText]}',
        doc: 'Adds a window specification to a window group, creating the group if necessary.',
    },
    GROUPCLOSE: {
        keyRawName: 'GroupClose',
        body: 'GroupClose, ${1:GroupName [}, ${2:A|R]}',
        doc: 'Closes the active window if it was just activated by GroupActivate or GroupDeactivate. It then activates the next window in the series. It can also close all windows in a group.',
    },
    GROUPDEACTIVATE: {
        keyRawName: 'GroupDeactivate',
        body: 'GroupDeactivate, ${1:GroupName [}, ${2:R]}',
        doc: 'Similar to GroupActivate except activates the next window not in the group.',
    },
    GUI: {
        keyRawName: 'Gui',
        body: 'Gui, ${1:sub-command [}, ${2:Param2}, ${3:Param3}, ${4:Param4]}',
        doc: 'Creates and manages windows and controls. Such windows can be used as data entry forms or custom user interfaces.',
    },
    GUICONTROL: {
        keyRawName: 'GuiControl',
        body: 'GuiControl, ${1:Sub-command}, ${2:ControlID [}, ${3:Param3]}',
        doc: 'Makes a variety of changes to a control in a GUI window.',
    },
    GUICONTROLGET: {
        keyRawName: 'GuiControlGet',
        body: 'GuiControlGet, ${1:OutputVar [}, ${2:Sub-command}, ${3:ControlID}, ${4:Param4]}',
        doc: 'Retrieves various types of information about a control in a GUI window.',
    },
    HOTKEY: {
        keyRawName: 'Hotkey',
        body: 'Hotkey, ${1:KeyName [}, ${2:Label}, ${3:Options]}',
        doc: 'Creates, modifies, enables, or disables a hotkey while the script is running.',
    },
    IFEXIST: {
        keyRawName: 'IfExist',
        body: 'IfExist, ${1:FilePattern}',
        doc: 'Checks for the existence of a file or folder.',
        recommended: false,
        diag: EDiagCode.code700,
        link: 'https://www.autohotkey.com/docs/commands/IfExist.htm',
        exp: [
            'IfExist, FilePattern',
            'IfNotExist, FilePattern',
            '',
            ';exp',
            'IfExist, D:\\Docs\\*.txt',
            '    MsgBox, At least one .txt file exists.',
        ],
    },
    IFINSTRING: {
        keyRawName: 'IfInString',
        body: 'IfInString, ${1:Var}, ${2:SearchString}',
        doc: 'Checks if a [variable](https://www.autohotkey.com/docs/Variables.htm) contains the specified string.',
        recommended: false,
        diag: EDiagCode.code700,
        link: 'https://www.autohotkey.com/docs/commands/IfInString.htm',
        exp: [
            'IfInString, Var, SearchString',
            'IfNotInString, Var, SearchString',
        ],
    },
    IFMSGBOX: {
        keyRawName: 'IfMsgBox',
        body: 'IfMsgBox, ${1:Yes|No|OK|Cancel|Abort|Ignore|Retry|Timeout}',
        doc: 'Checks which button was pushed by the user during the most recent MsgBox command.',
    },
    IFNOTEXIST: {
        keyRawName: 'IfNotExist',
        body: 'IfNotExist, ${1:FilePattern}',
        doc: 'Checks for the existence of a file or folder.',
        recommended: false,
        diag: EDiagCode.code700,
        link: 'https://www.autohotkey.com/docs/commands/IfExist.htm',
        exp: [
            'IfExist, FilePattern',
            'IfNotExist, FilePattern',
            '',
            ';exp',
            'IfExist, D:\\Docs\\*.txt',
            '    MsgBox, At least one .txt file exists.',
        ],
    },
    IFNOTINSTRING: {
        keyRawName: 'IfNotInString',
        body: 'IfNotInString, ${1:Var}, ${2:SearchString}',
        doc: 'Checks if a [variable](https://www.autohotkey.com/docs/Variables.htm) contains the specified string.',
        recommended: false,
        diag: EDiagCode.code700,
        link: 'https://www.autohotkey.com/docs/commands/IfInString.htm',
        exp: [
            'IfInString, Var, SearchString',
            'IfNotInString, Var, SearchString',
        ],
    },
    IFWINACTIVE: {
        keyRawName: 'IfWinActive',
        body: 'IfWinActive [, ${1:WinTitle}, ${2:WinText}, ${3:ExcludeTitle}, ${4:ExcludeText}]',
        doc: 'Checks if the specified window exists and is currently active (foremost).',
        recommended: false,
        diag: EDiagCode.code700,
        link: 'https://www.autohotkey.com/docs/commands/IfWinActive.htm',
        exp: [
            'IfWinActive [, WinTitle, WinText, ExcludeTitle, ExcludeText]',
            'IfWinNotActive [, WinTitle, WinText, ExcludeTitle, ExcludeText]',
        ],
    },
    IFWINEXIST: {
        keyRawName: 'IfWinExist',
        body: 'IfWinExist [, ${1:WinTitle}, ${2:WinText}, ${3:ExcludeTitle}, ${4:ExcludeText}]',
        doc: 'Checks if the specified window exists.',
        recommended: false,
        diag: EDiagCode.code700,
        link: 'https://www.autohotkey.com/docs/commands/IfWinExist.htm',
        exp: [
            'IfWinExist [, WinTitle, WinText, ExcludeTitle, ExcludeText]',
            'IfWinNotExist [, WinTitle, WinText, ExcludeTitle, ExcludeText]',
        ],
    },
    IFWINNOTACTIVE: {
        keyRawName: 'IfWinNotActive',
        body: 'IfWinNotActive [, ${1:WinTitle}, ${2:WinText}, ${3:ExcludeTitle}, ${4:ExcludeText}]',
        doc: 'Checks if the specified window exists and is currently active (foremost).',
        recommended: false,
        diag: EDiagCode.code700,
        link: 'https://www.autohotkey.com/docs/commands/IfWinActive.htm',
        exp: [
            'IfWinActive [, WinTitle, WinText, ExcludeTitle, ExcludeText]',
            'IfWinNotActive [, WinTitle, WinText, ExcludeTitle, ExcludeText]',
        ],
    },
    IFWINNOTEXIST: {
        keyRawName: 'IfWinNotExist',
        body: 'IfWinNotExist  [, ${1:WinTitle}, ${2:WinText}, ${3:ExcludeTitle}, ${4:ExcludeText}]',
        doc: 'Checks if the specified window exists.',
        recommended: false,
        diag: EDiagCode.code700,
        link: 'https://www.autohotkey.com/docs/commands/IfWinExist.htm',
        exp: [
            'IfWinExist [, WinTitle, WinText, ExcludeTitle, ExcludeText]',
            'IfWinNotExist [, WinTitle, WinText, ExcludeTitle, ExcludeText]',
        ],
    },
    IMAGESEARCH: {
        keyRawName: 'ImageSearch',
        body: 'ImageSearch, ${1:OutputVarX}, ${2:OutputVarY}, ${3:X1}, ${4:Y1}, ${5:X2}, ${6:Y2}, ${7:ImageFile}',
        doc: 'Searches a region of the screen for an image.',
    },
    INIDELETE: {
        keyRawName: 'IniDelete',
        body: 'IniDelete, ${1:Filename}, ${2:Section [}, ${3:Key]}',
        doc: 'Deletes a value from a standard format .ini file.',
    },
    INIREAD: {
        keyRawName: 'IniRead',
        body: 'IniRead, ${1:OutputVar}, ${2:Filename}, ${3:Section}, ${4:Key [}, ${5:Default]}',
        doc: 'Reads a value, section or list of section names from a standard format .ini file.',
    },
    INIWRITE: {
        keyRawName: 'IniWrite',
        body: 'IniWrite, ${1:Value}, ${2:Filename}, ${3:Section}, ${4:Key}',
        doc: 'Writes a value or section to a standard format .ini file.',
    },
    INPUT: {
        keyRawName: 'Input',
        body: 'Input, ${1:[ OutputVar}, ${2:Options}, ${3:EndKeys}, ${4:MatchList]}',
        doc: 'Waits for the user to type a string.',
    },
    INPUTBOX: {
        keyRawName: 'InputBox',
        body:
            'InputBox, ${1:OutputVar [}, ${2:Title}, ${3:Prompt}, ${4:HIDE}, ${5:Width}, ${6:Height}, ${7:X}, ${8:Y}, ${9:Font}, ${10:Timeout}',
        doc: 'Displays an input box to ask the user to enter a string.',
    },
    KEYHISTORY: {
        keyRawName: 'KeyHistory',
        body: 'KeyHistory',
        doc: 'Displays script info and a history of the most recent keystrokes and mouse clicks.',
    },
    KEYWAIT: {
        keyRawName: 'KeyWait',
        body: 'KeyWait, ${1:KeyName [}, ${2:Options]}',
        doc: 'Waits for a key or mouse/joystick button to be released or pressed down.',
    },
    LISTHOTKEYS: {
        keyRawName: 'ListHotkeys',
        body: 'ListHotkeys',
        doc: 'Displays the hotkeys in use by the current script, whether their subroutines are currently running, and whether or not they use the [keyboard](https://www.autohotkey.com/docs/commands/_InstallKeybdHook.htm) or [mouse](https://www.autohotkey.com/docs/commands/_InstallMouseHook.htm) hook.',
        recommended: true,
        link: 'https://www.autohotkey.com/docs/commands/ListHotkeys.htm',
        exp: ['ListHotkeys'],
    },
    LISTLINES: {
        keyRawName: 'ListLines',
        body: 'ListLines, ${1:[ On|Off]}',
        doc: 'Displays the script lines most recently executed.',
    },
    LISTVARS: {
        keyRawName: 'ListVars',
        body: 'ListVars',
        doc: 'Displays the script\'s [variables](https://www.autohotkey.com/docs/Variables.htm): their names and current contents.',
        recommended: true,
        link: 'https://www.autohotkey.com/docs/commands/ListVars.htm',
        exp: ['ListVars'],
    },
    LOCAL: {
        keyRawName: 'Local',
        body: 'local, ${1:VariableName}',
        doc: 'Local variables are specific to a single function and are visible only inside that function. Consequently, a local variable may have the same name as a global variable and both will have separate contents. Separate functions may also safely use the same variable names.',
        recommended: true,
        link: 'https://www.autohotkey.com/docs/Functions.htm#Local',
        exp: [
            'local a',
            'Local b := 0',
        ],
    },
    MENU: {
        keyRawName: 'Menu',
        body: 'Menu, ${1:MenuName}, ${2:Cmd [}, ${3:P3}, ${4:P4}, ${5:P5]}',
        doc: 'Creates, deletes, modifies and displays menus and menu items. Changes the tray icon and its tooltip. Controls whether the main window of a compiled script can be opened.',
    },
    MOUSECLICK: {
        keyRawName: 'MouseClick',
        body: 'MouseClick, ${1:WhichButton [}, ${2:X}, ${3:Y}, ${4:ClickCount}, ${5:Speed}, ${6:D|U}, ${7:R]}',
        doc: 'Clicks or holds down a mouse button, or turns the mouse wheel. NOTE: The Click command is generally more flexible and easier to use.',
    },
    MOUSECLICKDRAG: {
        keyRawName: 'MouseClickDrag',
        body: 'MouseClickDrag, ${1:WhichButton}, ${2:X1}, ${3:Y1}, ${4:X2}, ${5:Y2 [}, ${6:Speed}, ${7:R]}',
        doc: 'Clicks and holds the specified mouse button, moves the mouse to the destination coordinates, then releases the button.',
    },
    MOUSEGETPOS: {
        keyRawName: 'MouseGetPos',
        body: 'MouseGetPos, ${1:[ OutputVarX}, ${2:OutputVarY}, ${3:OutputVarWin}, ${4:OutputVarControl}, ${5:1|2|3]}',
        doc: 'Retrieves the current position of the mouse cursor, and optionally which window and control it is hovering over.',
    },
    MOUSEMOVE: {
        keyRawName: 'MouseMove',
        body: 'MouseMove, ${1:X}, ${2:Y [}, ${3:Speed}, ${4:R]}',
        doc: 'Moves the mouse cursor.',
    },
    MSGBOX: {
        keyRawName: 'MsgBox',
        body: 'MsgBox, % ${1:text}',
        doc: [
            'Displays the specified text in a small window containing one or more buttons (such as Yes and No).',
            '',
            '**Text** : type is string',
            '',
            '**Options** : type is number',
            '',
            '**Title** : type is string',
            '',
            '**Timeout** : type is number of second, exp: `10` or `% mins*60`',
            '',
        ].join('\n'),
        recommended: true,
        link: 'https://www.autohotkey.com/docs/commands/MsgBox.htm',
        exp: [
            'MsgBox, Text ;style1',
            'MsgBox, [Options, Title, Text, Timeout] ;style2',
            '',
            '; exp1 base of style1',
            'MsgBox, % "hello world!"',
            '',
            '',
            '; exp2 add `Buttons` -> `OK/Cancel` of 0x1 ',
            ';      and `Icon` -> `Icon Question` of 0x20',
            'MsgBox, % 0x1 + 0x20 ,% "exp2" ,% "Do you need help?"',
        ],
    },
    OUTPUTDEBUG: {
        keyRawName: 'OutputDebug',
        body: 'OutputDebug, ${1:, Text}${2: % }$3',
        doc: 'Sends a string to the debugger (if any) for display.',
    },
    PAUSE: {
        keyRawName: 'Pause',
        body: 'Pause, [ ${1|On,Off,Toggle|}, ${2|0,1|} ]',
        doc: 'Pauses the script\'s [current thread](https://www.autohotkey.com/docs/misc/Threads.htm).',
        recommended: true,
        link: 'https://www.autohotkey.com/docs/commands/Pause.htm',
        exp: [
            'Pause , OnOffToggle, OperateOnUnderlyingThread',
            '; exp',
            'Pause::Pause  ; The Pause/Break key.',
            '#p::Pause  ; Win+P',
        ],
    },
    PIXELGETCOLOR: {
        keyRawName: 'PixelGetColor',
        body: 'PixelGetColor, ${1:OutputVar}, ${2:X}, ${3:Y [}, ${4:Alt|Slow|RGB]}',
        doc: 'Retrieves the color of the pixel at the specified x,y coordinates.',
    },
    PIXELSEARCH: {
        keyRawName: 'PixelSearch',
        body:
            'PixelSearch, ${1:OutputVarX}, ${2:OutputVarY}, ${3:X1}, ${4:Y1}, ${5:X2}, ${6:Y2}, ${7:ColorID [}, ${8:Variation}',
        doc: 'Searches a region of the screen for a pixel of the specified color.',
    },
    POSTMESSAGE: {
        keyRawName: 'PostMessage',
        body:
            'PostMessage, ${1:Msg}, ${2:[wParam}, ${3:lParam}, ${4:Control}, ${5:WinTitle}, ${6:WinText}, ${7:ExcludeTitle}, ${8:ExcludeText]}',
        doc: 'Sends a message to a window or control (SendMessage additionally waits for acknowledgement).',
    },
    PROCESS: {
        keyRawName: 'Process',
        body: 'Process, ${1:Cmd}, ${2:PID-or-Name [}, ${3:Param3]}',
        doc: 'Performs one of the following operations on a process: checks if it exists; changes its priority; closes it; waits for it to close.',
    },
    RANDOM: {
        keyRawName: 'Random',
        body: 'Random, ${1:OutputVar [}, ${2:Min}, ${3:Max]}',
        doc: 'Generates a pseudo-random number.',
    },
    REGDELETE: {
        keyRawName: 'RegDelete',
        body: 'RegDelete, ${1:HKLM|HKU|HKCU|HKCR|HKCC}, ${2:SubKey [}, ${3:ValueName]}',
        doc: 'Deletes a subkey or value from the registry.',
    },
    REGREAD: {
        keyRawName: 'RegRead',
        body: 'RegRead, ${1:OutputVar}, ${2:HKLM|HKU|HKCU|HKCR|HKCC}, ${4:ValueName]}',
        doc: 'Reads a value from the registry.',
    },
    REGWRITE: {
        keyRawName: 'RegWrite',
        body:
            'RegWrite, ${1:REG_SZ|REG_EXPAND_SZ|REG_MULTI_SZ|REG_DWORD|REG_BINARY}, ${2:HKLM|HKU|HKCU|HKCR|HKCC}, ${3:SubKey [}, ${4:ValueName}, ${5:Value]}',
        doc: 'Writes a value to the registry.',
    },
    RUN: {
        keyRawName: 'Run',
        body: 'Run, ${1:Target [}, ${2:WorkingDir}, ${3:Max|Min|Hide|UseErrorLevel}, ${4:OutputVarPID]}',
        doc: 'Runs an external program.',
    },
    RUNAS: {
        keyRawName: 'RunAs',
        body: 'RunAs, ${1:[ User}, ${2:Password}, ${3:Domain]}',
        doc: 'Specifies a set of user credentials to use for all subsequent uses of Run and RunWait.',
    },
    RUNWAIT: {
        keyRawName: 'RunWait',
        body: 'RunWait, ${1:Target [}, ${2:WorkingDir}, ${3:Max|Min|Hide|UseErrorLevel}, ${4:OutputVarPID]}',
        doc: 'Unlike Run, RunWait will wait until the program finishes before continuing.',
    },
    SEND: {
        keyRawName: 'Send',
        body: 'Send, ${1:Keys}',
        doc: 'Sends simulated keystrokes and mouse clicks to the active window.',
    },
    SENDEVENT: {
        keyRawName: 'SendEvent',
        body: 'SendEvent, ${1:Keys}',
        doc: 'SendEvent sends keystrokes using the same method as the pre-1.0.43 Send command. The rate at which keystrokes are sent is determined by SetKeyDelay.',
    },
    SENDINPUT: {
        keyRawName: 'SendInput',
        body: 'SendInput, ${1:Keys}',
        doc: 'SendInput and SendPlay use the same syntax as Send but are generally faster and more reliable. In addition, they buffer any physical keyboard or mouse activity during the send, which prevents the user\'s keystrokes from being interspersed with those being sent.',
    },
    SENDLEVEL: {
        keyRawName: 'SendLevel',
        body: 'SendLevel, ${1:Level}',
        doc: 'Controls which artificial keyboard and mouse events are ignored by hotkeys and hotstrings.',
    },
    SENDMESSAGE: {
        keyRawName: 'SendMessage',
        body:
            'SendMessage, ${1:Msg}, ${2:[wParam}, ${3:lParam}, ${4:Control}, ${5:WinTitle}, ${6:WinText}, ${7:ExcludeTitle}, ${8:ExcludeText}, ${9:Timeout]}',
        doc: 'Sends a message to a window or control (SendMessage additionally waits for acknowledgement).',
    },
    SENDMODE: {
        keyRawName: 'SendMode',
        body: 'SendMode, ${1:Event|Play|Input|InputThenPlay}',
        doc: 'Makes Send synonymous with SendInput or SendPlay rather than the default (SendEvent). Also makes Click and MouseMove/Click/Drag use the specified method.',
    },
    SENDPLAY: {
        keyRawName: 'SendPlay',
        body: 'SendPlay, ${1:Keys}',
        doc: 'SendInput and SendPlay use the same syntax as Send but are generally faster and more reliable. In addition, they buffer any physical keyboard or mouse activity during the send, which prevents the user\'s keystrokes from being interspersed with those being sent.',
    },
    SENDRAW: {
        keyRawName: 'SendRaw',
        body: 'SendRaw, ${1:Keys}',
        doc: 'Similar to Send, except that all characters in Keys are interpreted and sent literally. See Raw mode for details.',
    },
    SETBATCHLINES: {
        keyRawName: 'SetBatchLines',
        body: 'SetBatchLines, ${1:-1 | 20ms | LineCount}',
        doc: 'Determines how fast a script will run (affects CPU utilization).',
    },
    SETCAPSLOCKSTATE: {
        keyRawName: 'SetCapsLockState',
        body: 'SetCapsLockState, ${1:On|Off|AlwaysOn|AlwaysOff}',
        doc: 'Sets the state of the CapsLock key. Can also force the key to stay on or off.',
    },
    SETCONTROLDELAY: {
        keyRawName: 'SetControlDelay',
        body: 'SetControlDelay, ${1:Delay}',
        doc: 'Sets the delay that will occur after each control-modifying command.',
    },
    SETDEFAULTMOUSESPEED: {
        keyRawName: 'SetDefaultMouseSpeed',
        body: 'SetDefaultMouseSpeed, ${1:Speed}',
        doc: 'Sets the mouse speed that will be used if unspecified in Click and MouseMove/Click/Drag.',
    },
    SETFORMAT: {
        keyRawName: 'SetFormat',
        body: 'SetFormat, NumberType, Format',
        doc: '**Deprecated:** This command is not recommended for use in new scripts. Use the [Format](https://www.autohotkey.com/docs/commands/Format.htm) function instead.',
        recommended: false,
        link: 'https://www.autohotkey.com/docs/commands/SetFormat.htm',
        exp: ['SetFormat, NumberType, Format'],
    },
    SETKEYDELAY: {
        keyRawName: 'SetKeyDelay',
        body: 'SetKeyDelay, ${1:[ Delay}, ${2:PressDuration]}',
        doc: 'Sets the delay that will occur after each keystroke sent by Send and ControlSend.',
    },
    SETMOUSEDELAY: {
        keyRawName: 'SetMouseDelay',
        body: 'SetMouseDelay, ${1:Delay}',
        doc: 'Sets the delay that will occur after each mouse movement or click.',
    },
    SETNUMLOCKSTATE: {
        keyRawName: 'SetNumLockState',
        body: 'SetNumLockState, ${1:On|Off|AlwaysOn|AlwaysOff}',
        doc: 'Sets the state of the NumLock key. Can also force the key to stay on or off.',
    },
    SETREGVIEW: {
        keyRawName: 'SetRegView',
        body: 'SetRegView, ${1:RegView}',
        doc: 'Sets the registry view used by RegRead, RegWrite, RegDelete and registry loops.',
    },
    SETSCROLLLOCKSTATE: {
        keyRawName: 'SetScrollLockState',
        body: 'SetScrollLockState, ${1:On|Off|AlwaysOn|AlwaysOff}',
        doc: 'Sets the state of the ScrollLock key. Can also force the key to stay on or off.',
    },
    SETSTORECAPSLOCKMODE: {
        keyRawName: 'SetStoreCapslockMode',
        body: 'SetStoreCapslockMode, ${1:On|Off}',
        doc: 'Whether to restore the state of CapsLock after a Send.',
    },
    SETTIMER: {
        keyRawName: 'SetTimer',
        body: 'SetTimer, ${1:Label [}, ${2:Period|On|Off]}',
        doc: 'Causes a subroutine to be launched automatically and repeatedly at a specified time interval.',
    },
    SETTITLEMATCHMODE: {
        keyRawName: 'SetTitleMatchMode',
        body: 'SetTitleMatchMode, ${1:Fast|Slow|RegEx|1|2|3}',
        doc: 'Sets the matching behavior of the WinTitle parameter in commands such as WinWait.',
    },
    SETWINDELAY: {
        keyRawName: 'SetWinDelay',
        body: 'SetWinDelay, ${1:Delay}',
        doc: 'Sets the delay that will occur after each windowing command, such as WinActivate.',
    },
    SETWORKINGDIR: {
        keyRawName: 'SetWorkingDir',
        body: 'SetWorkingDir, ${1:DirName}',
        doc: 'Changes the script\'s current working directory.',
    },
    SHUTDOWN: {
        keyRawName: 'Shutdown',
        body: 'Shutdown, ${1:Code}',
        doc: 'Shuts down, restarts, or logs off the system.',
    },
    SLEEP: {
        keyRawName: 'Sleep',
        body: 'Sleep, ${1:Delay}',
        doc: 'Waits the specified amount of time before continuing.',
    },
    SORT: {
        keyRawName: 'Sort',
        body: 'Sort, ${1:VarName [}, ${2:Options]}',
        doc: 'Arranges a variable\'s contents in alphabetical, numerical, or random order (optionally removing duplicates).',
    },
    SOUNDBEEP: {
        keyRawName: 'SoundBeep',
        body: 'SoundBeep, ${1:[ Frequency}, ${2:Duration]}',
        doc: 'Emits a tone from the PC speaker.',
    },
    SOUNDGET: {
        keyRawName: 'SoundGet',
        body: 'SoundGet, ${1:OutputVar [}, ${2:ComponentType}, ${3:ControlType}, ${4:DeviceNumber]}',
        doc: 'Retrieves various settings from a sound device (master mute, master volume, etc.)',
    },
    SOUNDGETWAVEVOLUME: {
        keyRawName: 'SoundGetWaveVolume',
        body: 'SoundGetWaveVolume, ${1:OutputVar [}, ${2:DeviceNumber]}',
        doc: 'Retrieves the wave output volume for a sound device.',
    },
    SOUNDPLAY: {
        keyRawName: 'SoundPlay',
        body: 'SoundPlay, ${1:Filename [}, ${2:wait]}',
        doc: 'Plays a sound, video, or other supported file type.',
    },
    SOUNDSET: {
        keyRawName: 'SoundSet',
        body: 'SoundSet, ${1:NewSetting}, ${2:[ComponentType}, ${3:ControlType}, ${4:DeviceNumber]}',
        doc: 'Changes various settings of a sound device (master mute, master volume, etc.)',
    },
    SOUNDSETWAVEVOLUME: {
        keyRawName: 'SoundSetWaveVolume',
        body: 'SoundSetWaveVolume, ${1:Percent [}, ${2:DeviceNumber]}',
        doc: 'Changes the wave output volume for a sound device.',
    },
    SPLITPATH: {
        keyRawName: 'SplitPath',
        body:
            'SplitPath, ${1:InputVar [}, ${2:OutFileName}, ${3:OutDir}, ${4:OutExtension}, ${5:OutNameNoExt}, ${6:OutDrive]}',
        doc: 'Separates a file name or URL into its name, directory, extension, and drive.',
    },
    STATIC: {
        keyRawName: 'Static',
        body: 'Static LoggedLines := 0',
        doc: 'Static variables are always implicitly local, but differ from locals because their values are remembered between calls.',
        recommended: true,
        link: 'https://www.autohotkey.com/docs/Functions.htm#static',
        exp: [
            'LogToFile(TextToLog)',
            '{',
            '    Static LoggedLines := 0',
            '    LoggedLines += 1  ; Maintain a tally locally (its value is remembered between calls).',
            '    global LogFileName',
            '    FileAppend, %LoggedLines%: %TextToLog%`n, %LogFileName%',
            '}',
        ],
    },
    STATUSBARGETTEXT: {
        keyRawName: 'StatusBarGetText',
        body:
            'StatusBarGetText, ${1:OutputVar [}, ${2:Part#}, ${3:WinTitle}, ${4:WinText}, ${5:ExcludeTitle}, ${6:ExcludeText]}',
        doc: 'Retrieves the text from a standard status bar control.',
    },
    STATUSBARWAIT: {
        keyRawName: 'StatusBarWait',
        body:
            'StatusBarWait, ${1:[BarText}, ${2:Seconds}, ${3:Part#}, ${4:WinTitle}, ${5:WinText}, ${6:Interval}, ${7:ExcludeTitle}, ${8:ExcludeText]}',
        doc: 'Waits until a window\'s status bar contains the specified string.',
    },
    STRINGCASESENSE: {
        keyRawName: 'StringCaseSense',
        body: 'StringCaseSense, ${1:On|Off|Locale}',
        doc: 'Determines whether string comparisons are case sensitive (default is "not case sensitive").',
    },
    STRINGGETPOS: {
        keyRawName: 'StringGetPos',
        body: 'StringGetPos, OutputVar, InputVar, SearchText , Occurrence, Offset',
        doc: 'Retrieves the position of the specified substring within a string.\n\n**Deprecated:** This command is not recommended for use in new scripts. Use the [InStr](https://www.autohotkey.com/docs/commands/InStr.htm) function instead.',
        recommended: false,
        link: 'https://www.autohotkey.com/docs/commands/StringGetPos.htm',
        exp: ['StringGetPos, OutputVar, InputVar, SearchText [, Occurrence, Offset]'],
        diag: EDiagCode.code700,
    },
    STRINGLEFT: {
        keyRawName: 'StringLeft',
        body: 'StringLeft, OutputVar, InputVar, Count',
        doc: 'Retrieves a number of characters from the left or right-hand side of a string.\n\n**Deprecated:** These commands are not recommended for use in new scripts. Use the [SubStr](https://www.autohotkey.com/docs/commands/SubStr.htm) function instead.',
        recommended: false,
        link: 'https://www.autohotkey.com/docs/commands/StringLeft.htm',
        exp: ['StringLeft, OutputVar, InputVar, Count'],
        diag: EDiagCode.code700,
    },
    STRINGLEN: {
        keyRawName: 'StringLen',
        body: 'StringLen, OutputVar, InputVar',
        doc: 'Retrieves the count of how many characters are in a string.\n\n**Deprecated:** This command is not recommended for use in new scripts. Use the [StrLen](https://www.autohotkey.com/docs/commands/StrLen.htm) function instead.',
        recommended: false,
        link: 'https://www.autohotkey.com/docs/commands/StringLen.htm',
        exp: ['StringLen, OutputVar, InputVar'],
        diag: EDiagCode.code700,
    },
    STRINGLOWER: {
        keyRawName: 'StringLower',
        body: 'StringLower, ${1:OutputVar}, ${2:InputVar} [, T]',
        doc: 'Converts a string to lowercase or uppercase.',
        recommended: false,
        link: 'https://www.autohotkey.com/docs/commands/StringLower.htm',
        exp: ['StringLower, OutputVar, InputVar , T'],
        diag: EDiagCode.code700,
    },
    STRINGMID: {
        keyRawName: 'StringMid',
        body: 'StringMid, OutputVar, InputVar, StartChar [, Count, L]',
        doc: 'Retrieves one or more characters from the specified position in a string.\n\n**Deprecated:** This command is not recommended for use in new scripts. Use the [SubStr](https://www.autohotkey.com/docs/commands/SubStr.htm) function instead.',
        recommended: false,
        link: 'https://www.autohotkey.com/docs/commands/StringMid.htm',
        exp: ['StringMid, OutputVar, InputVar, StartChar , Count, L'],
        diag: EDiagCode.code700,
    },
    STRINGREPLACE: {
        keyRawName: 'StringReplace',
        body: 'StringReplace, OutputVar, InputVar, SearchText , ReplaceText, ReplaceAll',
        doc: 'Replaces the specified substring with a new string.\n\n**Deprecated:** This command is not recommended for use in new scripts. Use the [StrReplace](https://www.autohotkey.com/docs/commands/StrReplace.htm) function instead.',
        recommended: false,
        link: 'https://www.autohotkey.com/docs/commands/StringReplace.htm',
        exp: ['StringReplace, OutputVar, InputVar, SearchText , ReplaceText, ReplaceAll'],
        diag: EDiagCode.code700,
    },
    STRINGRIGHT: {
        keyRawName: 'StringRight',
        body: 'StringRight, OutputVar, InputVar, Count',
        doc: 'Retrieves a number of characters from the left or right-hand side of a string.\n\n**Deprecated:** These commands are not recommended for use in new scripts. Use the [SubStr](https://www.autohotkey.com/docs/commands/SubStr.htm) function instead.',
        recommended: false,
        link: 'https://www.autohotkey.com/docs/commands/StringLeft.htm',
        exp: ['StringRight, OutputVar, InputVar, Count'],
        diag: EDiagCode.code700,
    },
    STRINGSPLIT: {
        keyRawName: 'StringSplit',
        body: 'StringSplit, ${1:OutputArray}, ${2:InputVar} [, ${3:Delimiters}, ${4:OmitChars}]',
        doc: 'Retrieves a number of characters from the left or right-hand side of a string.\n\n**Deprecated:** These commands are not recommended for use in new scripts. Use the [SubStr](https://www.autohotkey.com/docs/commands/SubStr.htm) function instead.',
        recommended: false,
        link: 'https://www.autohotkey.com/docs/commands/StringLeft.htm',
        exp: ['StringSplit, OutputArray, InputVar [, Delimiters, OmitChars]'],
        diag: EDiagCode.code700,
    },
    STRINGTRIMLEFT: {
        keyRawName: 'StringTrimLeft',
        body: 'StringTrimLeft, OutputVar, InputVar, Count',
        doc: 'Removes a number of characters from the left or right-hand side of a string.\n\n**Deprecated:** These commands are not recommended for use in new scripts. Use the [SubStr](https://www.autohotkey.com/docs/commands/SubStr.htm) function instead.',
        recommended: false,
        link: 'https://www.autohotkey.com/docs/commands/StringTrimLeft.htm',
        exp: ['StringTrimLeft, OutputVar, InputVar, Count'],
        diag: EDiagCode.code700,
    },
    STRINGTRIMRIGHT: {
        keyRawName: 'StringTrimRight',
        body: 'StringTrimRight, OutputVar, InputVar, Count',
        doc: 'Removes a number of characters from the left or right-hand side of a string.\n\n**Deprecated:** These commands are not recommended for use in new scripts. Use the [SubStr](https://www.autohotkey.com/docs/commands/SubStr.htm) function instead.',
        recommended: false,
        link: 'https://www.autohotkey.com/docs/commands/StringTrimLeft.htm',
        exp: ['StringTrimRight, OutputVar, InputVar, Count'],
        diag: EDiagCode.code700,
    },
    STRINGUPPER: {
        keyRawName: 'StringUpper',
        body: 'StringUpper, OutputVar, InputVar [, T]',
        doc: 'Converts a string to lowercase or uppercase.\n\nCommand -> func https://www.autohotkey.com/docs/Language.htm#commands-vs-functions',
        recommended: false,
        link: 'https://www.autohotkey.com/docs/commands/StringLower.htm',
        exp: ['StringUpper, OutputVar, InputVar , T'],
        diag: EDiagCode.code700,
    },
    SUSPEND: {
        keyRawName: 'Suspend',
        body: 'Suspend, ${1:[ On|Off|Toggle|Permit]}',
        doc: 'Disables or enables all or selected hotkeys and hotstrings.',
    },
    SYSGET: {
        keyRawName: 'SysGet',
        body: 'SysGet, ${1:OutputVar}, ${2:Sub-command [}, ${3:Param3]}',
        doc: 'Retrieves screen resolution, multi-monitor info, dimensions of system objects, and other system properties.',
    },
    THREAD: {
        keyRawName: 'Thread',
        body: 'Thread, ${1:NoTimers|Priority|Interrupt}',
        doc: 'Sets the priority or interruptibility of threads. It can also temporarily disable all timers.',
    },
    TOOLTIP: {
        keyRawName: 'ToolTip',
        body: 'ToolTip, ${1:[ Text}, ${2:X}, ${3:Y}, ${4:1_to_20]}',
        doc: 'Creates an always-on-top window anywhere on the screen.',
    },
    TRANSFORM: {
        keyRawName: 'Transform',
        body: 'Transform, OutputVar, SubCommand, Value1 [, Value2]',
        doc: 'Performs miscellaneous math functions, bitwise operations, and tasks such as ASCII/Unicode conversion.\n\n**Deprecated:** This command is not recommended for use in new scripts. For details on what you can use instead, see the sub-command sections below.',
        recommended: false,
        link: 'https://www.autohotkey.com/docs/commands/Transform.htm',
        exp: ['Transform, OutputVar, SubCommand, Value1 [, Value2]'],
    },
    TRAYTIP: {
        keyRawName: 'TrayTip',
        body: 'TrayTip, ${1:[ Title}, ${2:Text}, ${3:Seconds}, ${4:Options]}',
        doc: 'Creates a balloon message window near the tray icon. On Windows 10, a toast notification may be shown instead.',
    },
    URLDOWNLOADTOFILE: {
        keyRawName: 'UrlDownloadToFile',
        body: 'UrlDownloadToFile, ${1:URL}, ${2:Filename}',
        doc: 'Downloads a file from the Internet.',
    },

    WINACTIVATE: {
        keyRawName: 'WinActivate',
        body: 'WinActivate, ${1:[ WinTitle}, ${2:WinText}, ${3:ExcludeTitle}, ${4:ExcludeText]}',
        doc: 'Activates the specified window.',
    },
    WINACTIVATEBOTTOM: {
        keyRawName: 'WinActivateBottom',
        body: 'WinActivateBottom, ${1:[ WinTitle}, ${2:WinText}, ${3:ExcludeTitle}, ${4:ExcludeText]}',
        doc: 'Same as WinActivate except that it activates the bottommost matching window rather than the topmost.',
    },
    WINCLOSE: {
        keyRawName: 'WinClose',
        body: 'WinClose, ${1:[ WinTitle}, ${2:WinText}, ${3:SecondsToWait}, ${4:ExcludeTitle}, ${5:ExcludeText]}',
        doc: 'Closes the specified window.',
    },
    WINGET: {
        keyRawName: 'WinGet',
        body: 'WinGet, ${1:OutputVar [}, ${2:Cmd}, ${3:WinTitle}, ${4:WinText}, ${5:ExcludeTitle}, ${6:ExcludeText]}',
        doc: 'Retrieves the specified window\'s unique ID, process ID, process name, or a list of its controls. It can also retrieve a list of all windows matching the specified criteria.',
    },
    WINGETACTIVESTATS: {
        keyRawName: 'WinGetActiveStats',
        body: 'WinGetActiveStats, ${1:Title}, ${2:Width}, ${3:Height}, ${4:X}, ${5:Y}',
        doc: 'Combines the functions of WinGetActiveTitle and WinGetPos into one command.',
    },
    WINGETACTIVETITLE: {
        keyRawName: 'WinGetActiveTitle',
        body: 'WinGetActiveTitle, ${1:OutputVar}',
        doc: 'Retrieves the title of the active window.',
    },
    WINGETCLASS: {
        keyRawName: 'WinGetClass',
        body: 'WinGetClass, ${1:OutputVar [}, ${2:WinTitle}, ${3:WinText}, ${4:ExcludeTitle}, ${5:ExcludeText]}',
        doc: 'Retrieves the specified window\'s class name.',
    },
    WINGETPOS: {
        keyRawName: 'WinGetPos',
        body:
            'WinGetPos, ${1:[X}, ${2:Y}, ${3:Width}, ${4:Height}, ${5:WinTitle}, ${6:WinText}, ${7:ExcludeTitle}, ${8:ExcludeText]}',
        doc: 'Retrieves the position and size of the specified window.',
    },
    WINGETTEXT: {
        keyRawName: 'WinGetText',
        body: 'WinGetText, ${1:OutputVar [}, ${2:WinTitle}, ${3:WinText}, ${4:ExcludeTitle}, ${5:ExcludeText]}',
        doc: 'Retrieves the text from the specified window.',
    },
    WINGETTITLE: {
        keyRawName: 'WinGetTitle',
        body: 'WinGetTitle, ${1:OutputVar [}, ${2:WinTitle}, ${3:WinText}, ${4:ExcludeTitle}, ${5:ExcludeText]}',
        doc: 'Retrieves the title of the specified window.',
    },
    WINHIDE: {
        keyRawName: 'WinHide',
        body: 'WinHide,${1:[ WinTitle}, ${2:WinText}, ${3:ExcludeTitle}, ${4:ExcludeText]}',
        doc: 'Hides the specified window.',
    },
    WINKILL: {
        keyRawName: 'WinKill',
        body: 'WinKill,${1:[ WinTitle}, ${2:WinText}, ${3:SecondsToWait}, ${4:ExcludeTitle}, ${5:ExcludeText]}',
        doc: 'Forces the specified window to close.',
    },
    WINMAXIMIZE: {
        keyRawName: 'WinMaximize',
        body: 'WinMaximize, ${1:[ WinTitle}, ${2:WinText}, ${3:ExcludeTitle}, ${4:ExcludeText]}',
        doc: 'Enlarges the specified window to its maximum size.',
    },
    WINMENUSELECTITEM: {
        keyRawName: 'WinMenuSelectItem',
        body:
            'WinMenuSelectItem, ${1:WinTitle}, ${2:WinText}, ${3:Menu [}, ${4:SubMenu1}, ${5:SubMenu2}, ${6:SubMenu3}, ${7:SubMenu4}, ${8:SubMenu5}, ${9:SubMenu6}, ${10:ExcludeTitle}',
        doc: 'Invokes a menu item from the menu bar of the specified window.',
    },
    WINMINIMIZE: {
        keyRawName: 'WinMinimize',
        body: 'WinMinimize, ${1:[ WinTitle}, ${2:WinText}, ${3:ExcludeTitle}, ${4:ExcludeText]}',
        doc: 'Collapses the specified window into a button on the task bar.',
    },
    WINMINIMIZEALL: {
        keyRawName: 'WinMinimizeAll',
        body: 'WinMinimizeAll',
        doc: 'Minimizes all windows.',
    },
    WINMINIMIZEALLUNDO: {
        keyRawName: 'WinMinimizeAllUndo',
        body: 'WinMinimizeAllUndo',
        doc: 'Unminimizes all windows.',
    },
    WINMOVE: {
        keyRawName: 'WinMove',
        body:
            'WinMove, ${1:WinTitle}, ${2:WinText}, ${3:X}, ${4:Y}, ${5:[Width}, ${6:Height}, ${7:ExcludeTitle}, ${8:ExcludeText]}',
        doc: 'Changes the position and/or size of the specified window.',
    },
    WINRESTORE: {
        keyRawName: 'WinRestore',
        body: 'WinRestore, ${1:[ WinTitle}, ${2:WinText}, ${3:ExcludeTitle}, ${4:ExcludeText]}',
        doc: 'Unminimizes or unmaximizes the specified window if it is minimized or maximized.',
    },
    WINSET: {
        keyRawName: 'WinSet',
        body:
            'WinSet, ${1:AlwaysOnTop|Trans}, ${2:On|Off|Toggle|Value(0-255) [}, ${3:WinTitle}, ${4:WinText}, ${5:ExcludeTitle}, ${6:ExcludeText]}',
        doc: 'Makes a variety of changes to the specified window, such as "always on top" and transparency.',
    },
    WINSETTITLE: {
        keyRawName: 'WinSetTitle',
        body: 'WinSetTitle, ${1:WinTitle}, ${2:WinText}, ${3:NewTitle [}, ${4:ExcludeTitle}, ${5:ExcludeText]}',
        doc: 'Changes the title of the specified window.',
    },
    WINSHOW: {
        keyRawName: 'WinShow',
        body: 'WinShow, ${1:[ WinTitle}, ${2:WinText}, ${3:ExcludeTitle}, ${4:ExcludeText]}',
        doc: 'Unhides the specified window.',
    },
    WINWAIT: {
        keyRawName: 'WinWait',
        body: 'WinWait, ${1:WinTitle}, ${2:WinText}, ${3:Seconds [}, ${4:ExcludeTitle}, ${5:ExcludeText]}',
        doc: 'Waits until the specified window exists.',
    },
    WINWAITACTIVE: {
        keyRawName: 'WinWaitActive',
        body: 'WinWaitActive, ${1:[ WinTitle}, ${2:WinText}, ${3:Seconds}, ${4:ExcludeTitle}, ${5:ExcludeText]}',
        doc: 'Waits until the specified window is active.',
    },
    WINWAITCLOSE: {
        keyRawName: 'WinWaitClose',
        body: 'WinWaitClose, ${1:WinTitle}, ${2:WinText}, ${3:Seconds [}, ${4:ExcludeTitle}, ${5:ExcludeText]}',
        doc: 'Waits until the specified window does not exist.',
    },
    WINWAITNOTACTIVE: {
        keyRawName: 'WinWaitNotActive',
        body: 'WinWaitNotActive, ${1:[ WinTitle}, ${2:WinText}, ${3:Seconds}, ${4:ExcludeTitle}, ${5:ExcludeText]}',
        doc: 'Waits until the specified window is not active.',
    },
};
