/* eslint-disable max-lines */

import { LineCommand } from './Command';

// action_args = aLineText;

// TCHAR g_delimiter = ',';
// TCHAR g_DerefChar = '%';
// TCHAR g_EscapeChar = '`';

// g_act
// g_old_act
const g_act: string[] = [
    '-=',
    ':=',
    '',
    '',
    '',
    '',
    '"',
    '{',
    '}',
    '*=',
    '/=',
    '#if',
    '+=',
    '<',
    '<=',
    '<>',
    '=',
    '=',
    '>',
    '>=',
    'AutoTrim',
    'between',
    'BlockInput',
    'Break',
    'Case',
    'Catch',
    'Click',
    'ClipWait',
    'contains',
    'Continue',
    'Control',
    'ControlClick',
    'ControlFocus',
    'ControlGet',
    'ControlGetFocus',
    'ControlGetPos',
    'ControlGetText',
    'ControlMove',
    'ControlSend',
    'ControlSendRaw',
    'ControlSetText',
    'CoordMode',
    'Critical',
    'DetectHiddenText',
    'DetectHiddenWindows',
    'Drive',
    'DriveGet',
    'DriveSpaceFree',
    'Edit',
    'Else',
    'EnvGet',
    'EnvSet',
    'EnvUpdate',
    'Exit',
    'ExitApp',
    'FileAppend',
    'FileCopy',
    'FileCopyDir',
    'FileCreateDir',
    'FileCreateShortcut',
    'FileDelete',
    'FileEncoding',
    'FileGetAttrib',
    'FileGetShortcut',
    'FileGetSize',
    'FileGetTime',
    'FileGetVersion',
    'FileInstall',
    'FileMove',
    'FileMoveDir',
    'FileRead',
    'FileReadLine',
    'FileRecycle',
    'FileRecycleEmpty',
    'FileRemoveDir',
    'FileSelectFile',
    'FileSelectFolder',
    'FileSetAttrib',
    'FileSetTime',
    'Finally',
    'For',
    'FormatTime',
    'GetKeyState',
    'Gosub',
    'Goto',
    'GroupActivate',
    'GroupAdd',
    'GroupClose',
    'GroupDeactivate',
    'Gui',
    'GuiControl',
    'GuiControlGet',
    'Hotkey',
    'IfExist',
    'IfInString',
    'IfMsgBox',
    'IfNotExist',
    'IfNotInString',
    'IfWinActive',
    'IfWinExist',
    'IfWinNotActive',
    'IfWinNotExist',
    'ImageSearch',
    'in',
    'IniDelete',
    'IniRead',
    'IniWrite',
    'Input',
    'InputBox',
    'is not',
    'is',
    'KeyHistory',
    'KeyWait',
    'ListHotkeys',
    'ListLines',
    'ListVars',
    'Loop',
    'Menu',
    'MouseClick',
    'MouseClickDrag',
    'MouseGetPos',
    'MouseMove',
    'MsgBox',
    'not between',
    'not contains',
    'not in',
    'OnExit',
    'OutputDebug',
    'Pause',
    'PixelGetColor',
    'PixelSearch',
    'PostMessage',
    'Process',
    'Progress',
    'Random',
    'RegDelete',
    'RegRead',
    'RegWrite',
    'Reload',
    'Return',
    'Run',
    'RunAs',
    'RunWait',
    'Send',
    'SendEvent',
    'SendInput',
    'SendLevel',
    'SendMessage',
    'SendMode',
    'SendPlay',
    'SendRaw',
    'SetBatchLines',
    'SetCapslockState',
    'SetControlDelay',
    'SetDefaultMouseSpeed',
    'SetFormat',
    'SetKeyDelay',
    'SetMouseDelay',
    'SetNumlockState',
    'SetRegView',
    'SetScrollLockState',
    'SetStoreCapslockMode',
    'SetTimer',
    'SetTitleMatchMode',
    'SetWinDelay',
    'SetWorkingDir',
    'Shutdown',
    'Sleep',
    'Sort',
    'SoundBeep',
    'SoundGet',
    'SoundGetWaveVolume',
    'SoundPlay',
    'SoundSet',
    'SoundSetWaveVolume',
    'SplashImage',
    'SplashTextOff',
    'SplashTextOn',
    'SplitPath',
    'Static',
    'StatusBarGetText',
    'StatusBarWait',
    'StringCaseSense',
    'StringGetPos',
    'StringLeft',
    'StringLen',
    'StringLower',
    'StringMid',
    'StringReplace',
    'StringRight',
    'StringSplit',
    'StringTrimLeft',
    'StringTrimRight',
    'StringUpper',
    'Suspend',
    'Switch',
    'SysGet',
    'Thread',
    'Throw',
    'ToolTip',
    'Transform',
    'TrayTip',
    'Try',
    'Until',
    'URLDownloadToFile',
    'While',
    'WinActivate',
    'WinActivateBottom',
    'WinClose',
    'WinGet',
    'WinGetClass',
    'WinGetPos',
    'WinGetText',
    'WinGetTitle',
    'WinHide',
    'WinKill',
    'WinMaximize',
    'WinMenuSelectItem',
    'WinMinimize',
    'WinMinimizeAll',
    'WinMinimizeAllUndo',
    'WinMove',
    'WinRestore',
    'WinSet',
    'WinSetTitle',
    'WinShow',
    'WinWait',
    'WinWaitActive',
    'WinWaitClose',
    'WinWaitNotActive',

    'SetEnv',
    'EnvAdd',
    'EnvSub',
    'EnvMult',
    'EnvDiv',
    'IfEqual',
    'IfNotEqual',
    'IfGreater',
    'IfGreaterOrEqual',
    'IfLess',
    'IfLessOrEqual',
    'WinGetActiveTitle',
    'WinGetActiveStats',
];

const g_act_set = new Set(
    g_act
        .filter((v: string): boolean => (/^\w+$/u).test(v))
        .map((v: string): string => v.toUpperCase()),
);

const too_much: string[] = [];
for (const k of Object.keys(LineCommand)) {
    if (g_act_set.has(k)) {
        g_act_set.delete(k);
    } else {
        too_much.push(k);
    }
}

export const TODO_G_ACT = {
    too_much,
    too_little: [...g_act_set],
};
