// TODO js
// ComObjParameter
// IsByRef()
// ObjAddRef() / ObjRelease()
// ObjBindMethod()
// ObjClone()
// ObjClone()
// ObjCount()
// ObjCount()
// ObjDelete()
// ObjGetAddress()
// ObjGetBase()
// ObjGetCapacity()
// ObjHasKey()
// ObjInsert()
// ObjInsertAt()
// ObjLength()
// ObjMaxIndex()
// ObjMinIndex()
// ObjNewEnum()
// ObjPop()
// ObjPush()
// ObjRawGet()
// ObjRawSet()
// ObjRemove()
// ObjRemoveAt()
// ObjSetCapacity()

// TODO CommandList
// Edit
// EnvDiv
// EnvMult
// EnvUpdate
// ExitApp
// FileAppend
// Gosub
// Goto
// IfEqual
// IfExist
// IfGreater
// IfGreaterOrEqual
// IfInString
// IfLess
// IfLessOrEqual
// IfMsgBox
// IfNotEqual
// IfNotExist
// IfNotInString
// IfWinActive
// IfWinExist
// IfWinNotActive
// IfWinNotExist
// ListHotkeys
// ListVars
// Progress
// SetEnv
// SplashImage
// SplashTextOff
// SplashTextOff
// SplashTextOff
// StringSplit
